<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\pagedesigner\Definition\PatternDefinition;
use Drupal\ui_patterns\UiPatternsManager;


/**
 *  Implements hook_theme().
 */
function iq_barrio_theme($existing, $type, $theme, $path)
{
  return array();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function iq_barrio_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
  //    if ($node = \Drupal::routeMatch()->getParameter('node')) {
  //        $vid = \Drupal::routeMatch()->getParameter('node_revision');
  //        if (is_numeric($node)) {
  //            $node = \Drupal::entityTypeManager()
  //                ->getStorage('node')
  //                ->loadRevision($vid);
  //        }
  //        if (!is_numeric($vid) && $node->access('update', \Drupal::currentUser())) {
  //            $node = \Drupal::service('iq_block_module.node_collector')->getLatestRevision($node->id(), $node->language()->getId(), true);
  //        }
  //        $baseTypes = \Drupal::configFactory()->get('pagebuilder.settings')->get('contentTypes');
  //        if (in_array($node->getType(), $baseTypes) && $node->hasField('field_template')) {
  //            $template = $node->field_template->value;
  //            $term = Term::load($node->field_template->target_id);
  //            if ($term != null) {
  //                $suggestions[] = 'page__' . $term->field_template->value;
  //            }
  //        }
  //    }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */

function iq_barrio_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_iq_barrio_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _iq_barrio_user_login_form_submit($form, FormStateInterface $form_state)
{
  $form_state->setRedirect('<front>');
}

/**
 * Implements hook_form_system_theme_settings_alter().
 */
function iq_barrio_form_system_theme_settings_alter(&$form, FormStateInterface $form_state, $form_id = null)
{

//  $pattern_manager = new UiPatternsManager();
//
//  $definition = $pattern_manager->getDefinition('rowoneone');

//   $pattern_manager = \Drupal::service('plugin.manager.ui_patterns');

//   $pattern_definitions = $pattern_manager->getDefinitions();


//   $definition_src = $pattern_manager->getDefinition('rowoneone');

//   $pattern_definitions['rowoneone']['label'] = 'test test test';


//   $plugin_handler = \Drupal::service('plugin.manager.pagedesigner_handler');

// //  $plugin_handler->collectPatterns($pattern_definitions);



//   print_r( get_class_methods( $pattern_manager ) );

// echo "OK";

//  die();

  // $definition_src = \Drupal::service('plugin.manager.ui_patterns')->getDefinition('rowoneone');

  // print_r( $definition_src );

  // $additional_data = $definition_src->getAdditional();

  // $additional_data['classes']['random'] = [
  //   'label' => 'Random',
  //   'description' => 'I dont do anything',
  //   'responsive' => 1
  // ];


  // print_r( $additional_data );



  // $definition_src->setAdditional($additional_data);

  // $cid = 'rowoneone';

  // \Drupal::cache()->set($cid, $definition_src, Cache::PERMANENT, $block->getCacheTags());


  // print_r( $definition_src );


  // $definition['additional']['classes']['random'] = [
  //   'label]'=> 'Random',
  //   'description' => 'I dont do anything',
  //   'responsive' => 1
  // ];



  // $definition_src->setPropertyDefinition('label');


  // $definition['id'] = $id;
  // $patterns[] = $this->getPatternDefinition($definition);




  // $markup = \Drupal::service('renderer')->renderPlain($build);
  // $markup = '<div data-gjs-type="block">' . $markup . '<div>';
  // $definition['markup'] = $markup;
  // $definition['label'] = (string) $block->label();
  // $patterns[$id] = new PatternDefinition($definition);
  // \Drupal::cache()->set($cid, $definition, Cache::PERMANENT, $block->getCacheTags());








  $form['#attached']['library'][] = 'iq_barrio/admin-style';

  $arr_colors = [
    'Colors' => [
      'primary' => t('Primary color'),
      'secondary' => t('Secondary color'),
      'tertiary' => t('Tertiary color'),
      'quaternary' => t('Quaternary color'),
    ],
    'Greyscales' => [
      'grey1' => t('Grey 1'),
      'grey2' => t('Grey 2'),
      'grey3' => t('Grey 3'),
      'grey4' => t('Grey 4'),
      'grey5' => t('Grey 5'),
    ],
    'Constants' => [
      'black' => t('Black'),
      'white' => t('White'),
    ],
  ];

  $arr_fontweights = [
    '100' => t('100 (lightest)'),
    '200' => '200',
    '300' => t('300'),
    '400' => t('400 (normal)'),
    '500' => t('500'),
    '600' => t('600'),
    '700' => t('700 (bold)'),
    '800' => t('800'),
    '900' => t('900 (boldest)'),
  ];

  $arr_fontstyles = [
    'normal' => t('Normal'),
    'italic' => t('Italic'),
  ];

  $arr_units = [
    'px'  => 'px',
    'em'  => 'em',
    'rem' => 'rem',
    '%'   => '%'
  ];

  $arr_fonts = array(
    'System Fonts' => array(
      'Arial' => t('Arial'),
      'Courier New' => t('Courier New'),
      'Helvetica' => t('Helvetica'),
      'Times New Roman' => t('Times New Roman'),
      'Verdana' => t('Verdana'),
      '\'Open Sans\', sans-serif' => t('Open Sans, sans-serif'),
    ),
  );

  $moduleHandler = \Drupal::service('module_handler');

  if ($moduleHandler->moduleExists('fontyourface')) {
    $fonts = \Drupal\fontyourface\Entity\Font::loadActivatedFonts();

    if (!empty($fonts)) {


      foreach ($fonts as $font) {
        //Get "regular" fonts only
//        if ($font->css_style->value == 'normal' && $font->css_weight->value == 'normal') {
          $fontname = $font->name->value;
          $css_family = $font->css_family->value;

          $arr_google_fonts[$css_family] = $font->css_family->value;
//        }
      }
      $arr_fonts['Additional fonts'] = $arr_google_fonts;
    }
  }

  $form['iq_theme'] = [
    '#type' => 'vertical_tabs',
    '#title' => t('Custom Theme Settings'),
    '#attributes' => [
      'class' => ['iq-barrio-settings'],
    ]
  ];

  // section colors
  $form['color_definitions'] = [
    '#type' => 'details',
    '#title' => t('Colors'),
    '#open' => true, // Controls the HTML5 'open' attribute. Defaults to FALSE.
    '#group' => 'iq_theme',
    '#prefix' => '<div id="iq-barrio-target"></div><div id="iq-barrio-source">' . file_get_contents(__DIR__ . "/resources/sass/backend-styling-previes.css.txt") . '</div>'
  ];


  $form['color_definitions']['base_definitions'] = [
    '#type' => 'details',
    '#title' => t('Base color definitions'),
  ];

  $form['color_definitions']['base_definitions']['grey_holder'] = [
    '#type' => 'container',
    '#prefix' => '<strong>5 shades of grey</strong>',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field'],
    ]
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_black'] = [
    '#type' => 'hidden',
    '#default_value' => theme_get_setting('color_black') ? theme_get_setting('color_black') : '#000000',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_white'] = [
    '#type' => 'hidden',
    '#default_value' => theme_get_setting('color_white') ? theme_get_setting('color_white') : '#FFFFFF',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_black'] = [
    '#type' => 'hidden',
    '#default_value' => theme_get_setting('color_black') ? theme_get_setting('color_black') : '#000000',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_white'] = [
    '#type' => 'hidden',
    '#default_value' => theme_get_setting('color_white') ? theme_get_setting('color_white') : '#FFFFFF',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_grey1'] = [
    '#type' => 'color',
    '#default_value' => theme_get_setting('color_grey1') ? theme_get_setting('color_grey1') : '#333333',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_grey2'] = [
    '#type' => 'color',
    '#default_value' => theme_get_setting('color_grey2') ? theme_get_setting('color_grey2') : '#666666',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_grey3'] = [
    '#type' => 'color',
    '#default_value' => theme_get_setting('color_grey3') ? theme_get_setting('color_grey3') : '#999999',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_grey4'] = [
    '#type' => 'color',
    '#default_value' => theme_get_setting('color_grey4') ? theme_get_setting('color_grey4') : '#cccccc',
  ];

  $form['color_definitions']['base_definitions']['grey_holder']['color_grey5'] = [
    '#type' => 'color',
    '#default_value' => theme_get_setting('color_grey5') ? theme_get_setting('color_grey5') : '#eeeeee',
  ];


  $form['color_definitions']['base_definitions']['color_primary'] = [
    '#type' => 'color',
    '#title' => t('Primary color'),
    '#default_value' => theme_get_setting('color_primary') ? theme_get_setting('color_primary') : '#e95e27',
  ];

  $form['color_definitions']['base_definitions']['color_secondary'] = [
    '#type' => 'color',
    '#title' => t('Secondary color'),
    '#default_value' => theme_get_setting('color_secondary') ? theme_get_setting('color_secondary') : '#009C82',
  ];

  $form['color_definitions']['base_definitions']['color_tertiary'] = [
    '#type' => 'color',
    '#title' => t('Tertiary color'),
    '#default_value' => theme_get_setting('color_tertiary') ? theme_get_setting('color_tertiary') : '#9C360D',
  ];

  $form['color_definitions']['base_definitions']['color_quaternary'] = [
    '#type' => 'color',
    '#title' => t('Quaternary color'),
    '#default_value' => theme_get_setting('color_quaternary') ? theme_get_setting('color_quaternary') : '#27E9C9',
  ];

  $form['color_definitions']['section_definitions'] = [
    '#type' => 'details',
    '#title' => t('Color assignments'),
  ];

  $form['color_definitions']['section_definitions']['color_page_background'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background') ? theme_get_setting('color_page_background') : 'white',
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder separator"><strong>Page Background</strong>'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_background'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => '0.01',
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_background'),
    '#suffix' => '</div>'
  ];



  $form['color_definitions']['section_definitions']['color_page_background_meta_header'] = [
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_meta_header') ? theme_get_setting('color_page_background_meta_header') : 'white',
    '#prefix' => '<div class="inline-input-holder"><strong>Meta header</strong>'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_background_meta_header'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_background_meta_header'),
    '#suffix' => '</div>'
  ];



  $form['color_definitions']['section_definitions']['color_page_font_meta_header'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_meta_header') ? theme_get_setting('color_page_font_meta_header') : 'grey3',
    '#prefix' => '<div class="inline-input-holder separator">'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_font_meta_header'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_font_meta_header'),
    '#suffix' => '</div>'
  ];



  $form['color_definitions']['section_definitions']['color_page_background_header'] = [
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_header') ? theme_get_setting('color_page_background_header') : 'white',
    '#prefix' => '<div class="inline-input-holder"><strong>Header</strong>'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_background_header'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_background_header'),
    '#suffix' => '</div>'
  ];



  $form['color_definitions']['section_definitions']['color_page_font_header'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_header') ? theme_get_setting('color_page_font_header') : 'grey3',
    '#prefix' => '<div class="inline-input-holder separator">'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_font_header'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_font_header'),
    '#suffix' => '</div>'
  ];



  $form['color_definitions']['section_definitions']['color_page_background_footer'] = [
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_footer') ? theme_get_setting('color_page_background_footer') : 'grey5',
    '#prefix' => '<div class="inline-input-holder"><strong>Footer</strong>'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_background_footer'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_background_footer'),
    '#suffix' => '</div>'
  ];


  $form['color_definitions']['section_definitions']['color_page_font_footer'] = [
    '#type' => 'select',
    '#title' => t('Font color footer'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_footer') ? theme_get_setting('color_page_font_footer') : 'grey3',
    '#prefix' => '<div class="inline-input-holder separator">'
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_font_footer'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_font_footer'),
    '#suffix' => '</div>'
  ];



  $form['color_definitions']['section_definitions']['color_page_background_elements'] = [
    '#type' => 'select',
    '#title' => t('Background color '),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_elements') ? theme_get_setting('color_page_background_elements') : 'secondary',
    '#prefix' => '<div class="inline-input-holder separator"><strong>Elements (legacy)</strong>',
  ];

  $form['color_definitions']['section_definitions']['opacity_color_page_background_elements'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_color_page_background_elements'),
    '#suffix' => '</div></div><div class="styling-preview page-layout"><div id="color-definitions-preview-page"><div id="color-definitions-preview-meta-header">Meta header</div><div id="color-definitions-preview-header">Header</div><div id="color-definitions-preview-content">Content</div><div id="color-definitions-preview-footer">Footer</div></div></div></div>'
  ];


  // section typo
  $form['typography'] = [
    '#type' => 'details',
    '#title' => t('Typography'),
    '#summary' => t('Typography definitions.'),
    '#group' => 'iq_theme',
  ];

  $form['typography']['headings'] = [
    '#type' => 'details',
    '#title' => t('Headings'),
  ];

  $headings = [
    'h1' => 'Heading 1',
    'h2' => 'Heading 2',
    'h3' => 'Heading 3',
    'h4' => 'Heading 4',
    'h5' => 'Heading 5',
    'h6' => 'Heading 6',
  ];

  foreach ($headings as $tag => $title) {
    $font_family_value = theme_get_setting($tag . '_font_family') ? theme_get_setting($tag . '_font_family') : '000000';
    $color_value = theme_get_setting($tag . '_color') ? theme_get_setting($tag . '_color') : 'primary';
    $opacity_value = theme_get_setting($tag.'_opacity');
    $font_size_value = theme_get_setting($tag . '_font_size') ? theme_get_setting($tag . '_font_size') : '2.5';
    $font_size_unit_value = theme_get_setting($tag . '_font_size_unit') ? theme_get_setting($tag . '_font_size_unit') : 'rem';

    $font_size_min_value = theme_get_setting($tag . '_font_size_min') ? theme_get_setting($tag . '_font_size_min') : '2';

    $line_height_value = theme_get_setting($tag . '_line_height') ? theme_get_setting($tag . '_line_height') : '1.2';
    $font_weight_value = theme_get_setting($tag . '_font_weight') ? theme_get_setting($tag . '_font_weight') : 'normal';
    $font_style_value = theme_get_setting($tag . '_font_style') ? theme_get_setting($tag . '_font_style') : 'normal';

    $margin_top_value = theme_get_setting($tag . '_margin_top') ? theme_get_setting($tag . '_margin_top') : '0';
    $margin_bottom_value = theme_get_setting($tag . '_margin_bottom') ? theme_get_setting($tag . '_margin_bottom') : '30';
    $margin_unit_value = theme_get_setting($tag . '_margin_unit') ? theme_get_setting($tag . '_margin_unit') : 'px';



    $form['typography']['headings'][$tag . '_color'] = [
      '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>' . $title . '</strong>',
      '#type' => 'select',
      '#title' => t('Color'),
      '#options' => $arr_colors,
      '#default_value' => $color_value,
    ];


    $form['typography']['headings'][$tag . '_opacity'] = [
      '#type' => 'textfield',
      // '#attributes' => [
      //   'min' => 0,
      //   'max' => 1,
      //   'step' => 0.01,
      // ],
      '#title' => t('Opacity'),
      '#default_value' => $opacity_value,
      '#suffix' => '</div>'
    ];



    $form['typography']['headings'][$tag . '_font_family'] = [
      '#type' => 'select',
      '#title' => t('Font family'),
      '#options' => $arr_fonts,
      '#default_value' => $font_family_value,
      '#prefix' => '<div class="inline-input-holder">',
    ];


    $form['typography']['headings'][$tag . '_font_weight'] = [
      '#type' => 'select',
      '#options' => $arr_fontweights,
      '#title' => t('Font weight'),
      '#default_value' => $font_weight_value,
    ];


    $form['typography']['headings'][$tag . '_font_style'] = [
      '#type' => 'select',
      '#options' => $arr_fontstyles,
      '#title' => t('Font style'),
      '#default_value' => $font_style_value,
    ];



    $form['typography']['headings'][$tag . '_line_height'] = [
      '#type' => 'textfield',
      '#title' => t('Line height'),
      '#default_value' => $line_height_value,
      '#suffix' => '</div>'
    ];



    $form['typography']['headings'][$tag . '_font_size_min_holder'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['container-inline', 'unit-combo-field', 'separator'],
      ],
      '#prefix' => '<div class="inline-input-holder">',
    ];

    $form['typography']['headings'][$tag . '_font_size_min_holder'][$tag . '_font_size_min'] = [
      '#type' => 'textfield',
      '#title' => t('Font-size<br/>min'),
      '#default_value' => $font_size_min_value,
    ];



    $form['typography']['headings'][$tag . '_font_size_holder'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['container-inline', 'unit-combo-field', 'separator'],
      ]
    ];

    $form['typography']['headings'][$tag . '_font_size_holder'][$tag . '_font_size'] = [
      '#type' => 'textfield',
      '#title' => t('<br/>max'),
      '#default_value' => $font_size_value,
    ];

    $form['typography']['headings'][$tag . '_font_size_holder'][$tag . '_font_size_unit'] = [
      '#type' => 'select',
      '#options' => $arr_units,
      '#default_value' => $font_size_unit_value,
    ];



    $form['typography']['headings'][$tag . '_margin_holder'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
      ],
    ];
    $form['typography']['headings'][$tag . '_margin_holder'][$tag . '_margin_top'] = [
      '#title' => t('Margin (top, bottom)'),
      '#type' => 'textfield',
      '#default_value' => $margin_top_value,
    ];
    $form['typography']['headings'][$tag . '_margin_holder'][$tag . '_margin_bottom'] = [
      '#type' => 'textfield',
      '#default_value' => $margin_bottom_value,
    ];


    $form['typography']['headings'][$tag . '_margin_holder'][$tag . '_margin_unit'] = [
      '#type' => 'textfield',
      '#type' => 'select',
      '#options' => $arr_units,
      '#default_value' => $margin_unit_value,
      '#suffix' => '</div>'
    ];



    $form['typography']['headings'][$tag . '_title'] = [
      '#prefix' => '</div><div class="styling-preview">',
      '#suffix' => '</div></div>',
      '#type' => 'item',
      '#markup' => '<' . $tag . ' >' . $title . '</' . $tag . '><p>Next element<br/>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet</p>',
    ];
  }



  $form['typography']['text_elements'] = [
    '#type' => 'details',
    '#title' => t('Text elements'),
  ];

  $text_elements = [
    'standard' => 'Standard text font',
    'small' => 'Small text font',
    'lead' => 'Lead text font',
    'deco_1' => 'Decoration font 1',
    'deco_2' => 'Decoration font 2',
    'deco_3' => 'Decoration font 3',
  ];

  foreach ($text_elements as $tag => $title) {
    $font_family_value = theme_get_setting($tag . '_font_family') ? theme_get_setting($tag . '_font_family') : '000000';
    $color_value = theme_get_setting($tag . '_color') ? theme_get_setting($tag . '_color') : 'grey3';
    $opacity_value = theme_get_setting($tag.'_opacity');

    $font_size_min_value = theme_get_setting($tag . '_font_size_min') ? theme_get_setting($tag . '_font_size_min') : '1';
    $font_size_value = theme_get_setting($tag . '_font_size') ? theme_get_setting($tag . '_font_size') : '1.5';
    $font_size_unit_value = theme_get_setting($tag . '_font_size_unit') ? theme_get_setting($tag . '_font_size_unit') : 'rem';
    $line_height_value = theme_get_setting($tag . '_line_height') ? theme_get_setting($tag . '_line_height') : '1.2';
    $font_weight_value = theme_get_setting($tag . '_font_weight') ? theme_get_setting($tag . '_font_weight') : '400';
    $font_style_value = theme_get_setting($tag . '_font_style') ? theme_get_setting($tag . '_font_style') : 'normal';

    $margin_top_value = theme_get_setting($tag . '_margin_top') ? theme_get_setting($tag . '_margin_top') : '0';
    $margin_bottom_value = theme_get_setting($tag . '_margin_bottom') ? theme_get_setting($tag . '_margin_bottom') : '0.5';
    $margin_unit_value = theme_get_setting($tag . '_margin_unit') ? theme_get_setting($tag . '_margin_unit') : 'rem';


    $form['typography']['text_elements'][$tag . '_color'] = [
      '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>' . $title . '</strong>',
      '#type' => 'select',
      '#title' => t('Color'),
      '#options' => $arr_colors,
      '#default_value' => $color_value,
    ];

    $form['typography']['text_elements'][$tag . '_opacity'] = [
      '#type' => 'textfield',
      // '#attributes' => [
      //   'min' => 0,
      //   'max' => 1,
      //   'step' => 0.01,
      // ],
      '#title' => t('Opacity'),
      '#default_value' => $opacity_value,
      '#suffix' => '</div>'
    ];

    $form['typography']['text_elements'][$tag . '_font_family'] = [
      '#type' => 'select',
      '#title' => t('Font family'),
      '#options' => $arr_fonts,
      '#default_value' => $font_family_value,
      '#prefix' => '<div class="inline-input-holder">',
    ];

    $form['typography']['text_elements'][$tag . '_font_weight'] = [
      '#type' => 'select',
      '#options' => $arr_fontweights,
      '#title' => t('Font weight'),
      '#default_value' => $font_weight_value,
    ];

    $form['typography']['text_elements'][$tag . '_font_style'] = [
      '#type' => 'select',
      '#options' => $arr_fontstyles,
      '#title' => t('Font style'),
      '#default_value' => $font_style_value,
    ];

    $form['typography']['text_elements'][$tag . '_line_height'] = [
      '#type' => 'textfield',
      '#title' => t('Line height'),
      '#default_value' => $line_height_value,
      '#suffix' => '</div>'
    ];






    $form['typography']['text_elements'][$tag . '_font_size_min_holder'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['container-inline', 'unit-combo-field', 'separator'],
      ],
      '#prefix' => '<div class="inline-input-holder">',
    ];

    $form['typography']['text_elements'][$tag . '_font_size_min_holder'][$tag . '_font_size_min'] = [
      '#type' => 'textfield',
      '#title' => t('Font-size<br/>min'),
      '#default_value' => $font_size_min_value,
    ];



    $form['typography']['text_elements'][$tag . '_font_size_holder'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['container-inline', 'unit-combo-field', 'separator'],
      ]
    ];

    $form['typography']['text_elements'][$tag . '_font_size_holder'][$tag . '_font_size'] = [
      '#type' => 'textfield',
      '#title' => t('<br/>max'),
      '#default_value' => $font_size_value,
    ];

    $form['typography']['text_elements'][$tag . '_font_size_holder'][$tag . '_font_size_unit'] = [
      '#type' => 'select',
      '#options' => $arr_units,
      '#default_value' => $font_size_unit_value,
    ];


    $form['typography']['text_elements'][$tag . '_margin_holder'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
      ],
    ];
    $form['typography']['text_elements'][$tag . '_margin_holder'][$tag . '_margin_top'] = [
      '#title' => t('Margin (top, bottom)'),
      '#type' => 'textfield',
      '#default_value' => $margin_top_value,
    ];
    $form['typography']['text_elements'][$tag . '_margin_holder'][$tag . '_margin_bottom'] = [
      '#type' => 'textfield',
      '#default_value' => $margin_bottom_value,
    ];


    $form['typography']['text_elements'][$tag . '_margin_holder'][$tag . '_margin_unit'] = [
      '#type' => 'textfield',
      '#type' => 'select',
      '#options' => $arr_units,
      '#default_value' => $margin_unit_value,
      '#suffix' => '</div>'
    ];



    $form['typography']['text_elements'][$tag . '_title'] = [
      '#prefix' => '</div><div class="styling-preview">',
      '#suffix' => '</div></div>',
      '#type' => 'item',
      '#markup' => '<p class="' . $tag . '">' . $title . '<br/>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet</p>',
    ];
  }



  $form['typography']['text_elements']['color_text_inverted'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_text_inverted') ? theme_get_setting('color_text_inverted') : 'white',
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>Inverted text</strong>',
  ];

  $form['typography']['text_elements']['opacity_text_inverted'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_text_inverted'),
    '#suffix' => '</div></div></div>'
  ];



  $form['typography']['links'] = [
    '#type' => 'details',
    '#title' => t('Links'),
  ];

  $link_color_value = theme_get_setting('link_color') ? theme_get_setting('link_color') : 'primary';
  $link_opacity_value = theme_get_setting('link_opacity');
  $link_text_decoration_value = theme_get_setting('link_text_decoration') ? theme_get_setting('link_text_decoration') : 'underline';

  $link_color_hover_value = theme_get_setting('link_color_hover') ? theme_get_setting('link_color_hover') : 'primary';
  $link_opacity_hover_value = theme_get_setting('link_opacity_hover');


  $link_text_decoration_hover_value = theme_get_setting('link_text_decoration_hover') ? theme_get_setting('link_text_decoration_hover') : 'underline';

  $form['typography']['links']['link_color'] = [
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder separator"><strong>Standard</strong>',
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => $link_color_value,
  ];

  $form['typography']['links']['link_opacity'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => $link_opacity_value,
  ];

  $form['typography']['links']['link_text_decoration'] = [
    '#type' => 'select',
    '#title' => t('Text decoration'),
    '#options' => [
      'underline' => t('Underline'),
      'underline dotted' => t('Dotted'),
      'underline dashed' => t('Dashed'),
      'none' => t('none'),
    ],
    '#default_value' => $link_text_decoration_value,
    '#suffix' => '</div>'
  ];



  $form['typography']['links']['link_color_hover'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => $link_color_hover_value,
    '#prefix' => '<div class="inline-input-holder separator"><strong>Hover</strong>',
  ];


  $form['typography']['links']['link_opacity_hover'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => $link_opacity_hover_value,
  ];


  $form['typography']['links']['link_text_decoration_hover'] = [
    '#type' => 'select',
    '#title' => t('Text decoration'),
    '#options' => [
      'underline' => t('Underline'),
      'underline dotted' => t('Dotted'),
      'underline dashed' => t('Dashed'),
      'none' => t('none'),
    ],
    '#default_value' => $link_text_decoration_hover_value,
    '#suffix' => '</div>'
  ];

  $form['typography']['links']['link_title'] = [
    '#prefix' => '</div><div class="styling-preview">',
    '#suffix' => '</div></div>',
    '#type' => 'item',
    '#markup' => '<p>Links: </p><p><a href="#" class="preview-link-standard">Standard</a></p><p><a href="#" class="preview-link-hover">Hovered</a></p><p>Inline links within text: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor <a href="#" class="preview-link-inline">invidunt</a> ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd <a href="#" class="preview-link-inline">gubergren, no sea takimata sanctus est</a> Lorem ipsum dolor sit amet</p>',
  ];


  // section decorations

  $form['navigation'] = [
    '#type' => 'details',
    '#title' => t('Navigation'),
    '#summary' => t('Navigation settings'),
    '#group' => 'iq_theme',
  ];


  $form['navigation']['navi_main'] = [
    '#type' => 'details',
    '#title' => t('Navigation Main'),
  ];

  $form['navigation']['navi_main']['navi_main_font_family'] = [
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>Base styling</strong>',
    '#type' => 'select',
    '#title' => t('Font family'),
    '#options' => $arr_fonts,
    '#default_value' => theme_get_setting('navi_main_font_family'),
  ];

  $form['navigation']['navi_main']['navi_main_font_weight'] = [
    '#type' => 'select',
    '#options' => $arr_fontweights,
    '#title' => t('Font weight'),
    '#default_value' => theme_get_setting('navi_main_font_weight'),
  ];

  $form['navigation']['navi_main']['navi_main_font_style'] = [
    '#type' => 'select',
    '#options' => $arr_fontstyles,
    '#title' => t('Font style'),
    '#default_value' => theme_get_setting('navi_main_font_style'),
  ];



  $form['navigation']['navi_main']['navi_main_line_height'] = [
    '#type' => 'textfield',
    '#title' => t('Line height'),
    '#default_value' => theme_get_setting('navi_main_line_height'),
    '#suffix' => '</div>'
  ];



  $form['navigation']['navi_main']['navi_main_font_size_holder'] = [
    '#type' => 'container',
    '#prefix' => '<div class="inline-input-holder separator">',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'separator'],
    ]
  ];

  $form['navigation']['navi_main']['navi_main_font_size_holder']['navi_main_font_size'] = [
    '#type' => 'textfield',
    '#title' => t('Font size'),
    '#default_value' => theme_get_setting('navi_main_font_size'),
  ];

  $form['navigation']['navi_main']['navi_main_font_size_holder']['navi_main_font_size_unit'] = [
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('navi_main_font_size_unit'),
  ];


  $form['navigation']['navi_main']['navi_main_margin_holder'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
    ],
  ];

  $form['navigation']['navi_main']['navi_main_margin_holder']['navi_main_margin_top'] = [
    '#title' => t('Margin (top, left/right, bottom)'),
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('navi_main_margin_top'),
  ];

  $form['navigation']['navi_main']['navi_main_margin_holder']['navi_main_margin_left_right'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('navi_main_margin_left_right'),
  ];

  $form['navigation']['navi_main']['navi_main_margin_holder']['navi_main_margin_bottom'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('navi_main_margin_bottom'),
  ];

  $form['navigation']['navi_main']['navi_main_margin_holder']['navi_main_margin_unit'] = [
    '#type' => 'textfield',
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('navi_main_margin_unit'),
  ];


  $form['navigation']['navi_main']['navi_main_padding_holder'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
    ],
    '#suffix' => '</div>'
  ];

  $form['navigation']['navi_main']['navi_main_padding_holder']['navi_main_padding_top'] = [
    '#title' => t('Padding (top, left/right, bottom)'),
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('navi_main_padding_top'),
  ];

  $form['navigation']['navi_main']['navi_main_padding_holder']['navi_main_padding_left_right'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('navi_main_padding_left_right'),
  ];

  $form['navigation']['navi_main']['navi_main_padding_holder']['navi_main_padding_bottom'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('navi_main_padding_bottom'),
  ];

  $form['navigation']['navi_main']['navi_main_padding_holder']['navi_main_padding_unit'] = [
    '#type' => 'textfield',
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('navi_main_padding_unit'),
  ];






  $form['navigation']['navi_main']['color_page_background_navbar'] = [
    '#prefix' => '<div class="inline-input-holder"><strong>Standard</strong>',
    '#type' => 'select',
    '#title' => t('Background color '),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_navbar') ? theme_get_setting('color_page_background_navbar') : 'white',
  ];

  $form['navigation']['navi_main']['opacity_page_background_navbar'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_navbar'),
  ];

  $form['navigation']['navi_main']['color_page_font_navbar'] = [
    '#type' => 'select',
    '#title' => t('Font color '),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_navbar') ? theme_get_setting('color_page_font_navbar') : 'grey3',
  ];

  $form['navigation']['navi_main']['opacity_page_font_navbar'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_navbar'),
    '#suffix' => '</div>'
  ];

  $form['navigation']['navi_main']['color_page_background_navbar_hover'] = [
    '#prefix' => '<div class="inline-input-holder"><strong>Navbar hover</strong>',
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_navbar_hover') ? theme_get_setting('color_page_background_navbar_hover') : 'primary',
  ];

  $form['navigation']['navi_main']['opacity_page_background_navbar_hover'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_navbar_hover'),
  ];

  $form['navigation']['navi_main']['color_page_font_navbar_hover'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_navbar_hover') ? theme_get_setting('color_page_font_navbar_hover') : 'white',
  ];

  $form['navigation']['navi_main']['opacity_page_font_navbar_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_navbar_hover'),
    '#suffix' => '</div>'
  ];



  $form['navigation']['navi_main']['color_page_background_navbar_active'] = [
    '#prefix' => '<div class="inline-input-holder separator"><strong>Navbar active</strong>',
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_navbar_active') ? theme_get_setting('color_page_background_navbar_active') : 'primary',
  ];

  $form['navigation']['navi_main']['opacity_page_background_navbar_active'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_navbar_active'),
  ];

  $form['navigation']['navi_main']['color_page_font_navbar_active'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_navbar_active') ? theme_get_setting('color_page_font_navbar_active') : 'black',
  ];

  $form['navigation']['navi_main']['opacity_page_font_navbar_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_navbar_active'),
    '#suffix' => '</div>'
  ];


  $form['navigation']['navi_main']['color_page_background_nav_dropdown'] = [
    '#prefix' => '<div class="inline-input-holder"><strong>Dropdown standard</strong>',
    '#type' => 'select',
    '#title' => t('Background'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_nav_dropdown') ? theme_get_setting('color_page_background_nav_dropdown') : 'primary',
  ];

  $form['navigation']['navi_main']['opacity_page_background_nav_dropdown'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_nav_dropdown'),
  ];

  $form['navigation']['navi_main']['color_page_font_nav_dropdown'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_dropdown') ? theme_get_setting('color_page_font_nav_dropdown') : 'grey3',
  ];

  $form['navigation']['navi_main']['opacity_page_font_nav_dropdown'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_dropdown'),
    '#suffix' => '</div>'
  ];

  $form['navigation']['navi_main']['color_page_background_nav_dropdown_hover'] = [
    '#prefix' => '<div class="inline-input-holder"><strong>Dropdown hover</strong>',
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_nav_dropdown_hover') ? theme_get_setting('color_page_background_nav_dropdown_hover') : 'primary',
    '#suffix' => '<div class="line-break"></div>'
  ];

  $form['navigation']['navi_main']['opacity_page_background_nav_dropdown_hover'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_nav_dropdown_hover'),
  ];

  $form['navigation']['navi_main']['color_page_font_nav_dropdown_hover'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_dropdown_hover') ? theme_get_setting('color_page_font_nav_dropdown_hover') : 'grey3',
  ];

  $form['navigation']['navi_main']['opacity_page_font_nav_dropdown_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_dropdown_hover'),
    '#suffix' => '</div>'
  ];

  $form['navigation']['navi_main']['color_page_background_nav_dropdown_active'] = [
    '#prefix' => '<div class="inline-input-holder"><strong>Dropdown active</strong>',
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_nav_dropdown_active') ? theme_get_setting('color_page_background_nav_dropdown_active') : 'primary',
    '#suffix' => '<div class="line-break"></div>'
  ];

  $form['navigation']['navi_main']['opacity_page_background_nav_dropdown_active'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_nav_dropdown_active'),
  ];

  $form['navigation']['navi_main']['color_page_font_nav_dropdown_active'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_dropdown_active') ? theme_get_setting('color_page_font_nav_dropdown_active') : 'grey3',
  ];

  $form['navigation']['navi_main']['opacity_page_font_nav_dropdown_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_dropdown_active'),
    '#suffix' => '</div>'
  ];


  $form['navigation']['navi_main']['navi_main_title'] = [
    '#prefix' => '</div><div class="styling-preview">',
    '#suffix' => '</div></div>',
    '#type' => 'item',
    '#markup' => '<ul class="clearfix nav navbar-nav">
      <li class="nav-item">
        <a href="#" class="nav-link" >Main Nav 1</a>
      </li>
      <li class="nav-item menu-item--expanded active dropdown">
        <a href="#" class="nav-link active dropdown-toggle" >Main Nav 2 (active)</a>
        <ul class="dropdown-menu">
          <li class="dropdown-item">
            <a href="#" >Nav Dropdown 1</a>
          </li>
          <li class="dropdown-item active">
            <a href="#" class="active is-active" >Nav Dropdown 2 (active)</a>
          </li>
          <li class="dropdown-item">
            <a href="#" >Nav Dropdown 3</a>
          </li>
        </ul>
      </li>
      <li class="nav-item">
        <a href="/de/raster" class="nav-link" >Main Nav 3</a>
      </li>
      <li class="nav-item">
        <a href="/de/raster" class="nav-link" >Main Nav 4</a>
      </li>
    </ul>',
  ];




  $form['navigation']['navi_mobile'] = [
    '#type' => 'details',
    '#title' => t('Navigation Mobile'),
  ];

  $form['navigation']['navi_mobile']['color_page_background_nav_mobile'] = [
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder separator"><strong>Mobile navigation</strong>',
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_background_nav_mobile') ? theme_get_setting('color_page_background_nav_mobile') : 'white',
  ];

  $form['navigation']['navi_mobile']['opacity_page_background_nav_mobile'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => ['separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_background_nav_mobile'),
  ];

  $form['navigation']['navi_mobile']['color_page_font_nav_mobile'] = [
    '#type' => 'select',
    '#title' => t('Font color '),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_mobile') ? theme_get_setting('color_page_font_nav_mobile') : 'grey3',
  ];

  $form['navigation']['navi_mobile']['opacity_page_font_nav_mobile'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_mobile'),
    '#suffix' => '</div>'
  ];


  $form['navigation']['navi_mobile']['color_page_font_nav_mobile_hover'] = [
    '#prefix' => '<div class="inline-input-holder"><strong>Mobile navigation hover</strong>',
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_mobile_hover') ? theme_get_setting('color_page_font_nav_mobile_hover') : 'grey3',
  ];

  $form['navigation']['navi_mobile']['opacity_page_font_nav_mobile_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_mobile_hover'),
    '#suffix' => '</div>'
  ];


  $form['navigation']['navi_mobile']['navi_mobile_title'] = [
    '#prefix' => '</div><div class="styling-preview">',
    '#suffix' => '</div></div>',
    '#type' => 'item',
    '#markup' => 'Preview',
  ];







  $form['navigation']['navi_sidebar'] = [
    '#type' => 'details',
    '#title' => t('Navigation Sidebar'),
  ];


  $form['navigation']['navi_sidebar']['color_page_font_nav_sidebar'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_sidebar') ? theme_get_setting('color_page_font_nav_sidebar') : 'grey3',
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder separator"><strong>Sidebar standard</strong>',
  ];

  $form['navigation']['navi_sidebar']['opacity_page_font_nav_sidebar'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_sidebar'),
    '#suffix' => '</div>'
  ];


  $form['navigation']['navi_sidebar']['color_page_font_nav_sidebar_hover'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_page_font_nav_sidebar_hover') ? theme_get_setting('color_page_font_nav_sidebar_hover') : 'grey3',
    '#prefix' => '<div class="inline-input-holder separator"><strong>Sidebar hover</strong>',
  ];

  $form['navigation']['navi_sidebar']['opacity_page_font_nav_sidebar_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_page_font_nav_sidebar_hover'),
    '#suffix' => '</div>'
  ];


  $form['navigation']['navi_sidebar']['navi_sidebar_title'] = [
    '#prefix' => '</div><div class="styling-preview">',
    '#suffix' => '</div></div>',
    '#type' => 'item',
    '#markup' => 'Preview',
  ];


  // section decorations

  $form['decorations'] = [
    '#type' => 'details',
    '#title' => t('Styling'),
    '#summary' => t('Borders, shadows etc.'),
    '#group' => 'iq_theme',
  ];


  $form['decorations']['border'] = [
    '#type' => 'details',
    '#title' => t('Border'),
  ];


  $form['decorations']['border']['border_width_holder'] = [
    '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder ">',
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'separator'],
    ]
  ];

  $form['decorations']['border']['border_width_holder']['border_width'] = [
    '#type' => 'textfield',
    '#title' => t('Width'),
    '#default_value' => theme_get_setting('border_width') ? theme_get_setting('border_width') : '1',
  ];

  $form['decorations']['border']['border_width_holder']['border_width_unit'] = [
    '#type' => 'textfield',
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('border_width_unit') ? theme_get_setting('border_width_unit') : '1',
  ];



  $form['decorations']['border']['border_style'] = [
    '#type' => 'select',
    '#title' => t('Style'),
    '#options' => [
      'dotted' => 'Dotted',
      'dashed' => 'Dashed',
      'solid' => 'Solid',
      'double' => 'Double',
      'groove' => 'Groove',
      'ridge' => 'Ridge',
      'inset' => 'Inset',
      'outset' => 'Outset',
    ],
    '#attributes' => [
      'class' => ['separator'],
    ],
    '#default_value' => theme_get_setting('border_style') ? theme_get_setting('border_style') : 'solid',
  ];



  $form['decorations']['border']['border_color'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('border_color') ? theme_get_setting('border_color') : 'primary',
  ];

  $form['decorations']['border']['border_opacity'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('border_opacity'),
    '#suffix' => '</div>'
  ];




  $form['decorations']['border']['radius_holder'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field'],
    ]
  ];

  $form['decorations']['border']['radius_holder']['radius'] = [
    '#type' => 'textfield',
    '#title' => t('Border Radius'),
    '#default_value' => theme_get_setting('radius') ? theme_get_setting('radius') : '1',
  ];

  $form['decorations']['border']['radius_holder']['radius_unit'] = [
    '#type' => 'textfield',
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('radius_unit') ? theme_get_setting('radius_unit') : '1',
    '#suffix' => '</div></div>'
  ];


  $form['decorations']['margins_paddings'] = [
    '#type' => 'details',
    '#title' => t('Margins & Paddings'),
  ];


  $form['decorations']['margins_paddings']['margin'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
    ],
  ];

  $form['decorations']['margins_paddings']['margin']['margin_top'] = [
    '#title' => t('Margin (Top, right, bottom, left)'),
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('margin_top') ? theme_get_setting('margin_top') : '30',
  ];

  $form['decorations']['margins_paddings']['margin']['margin_right'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('margin_right') ? theme_get_setting('margin_right') : '30',
  ];

  $form['decorations']['margins_paddings']['margin']['margin_bottom'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('margin_bottom') ? theme_get_setting('margin_bottom') : '30',
  ];

  $form['decorations']['margins_paddings']['margin']['margin_left'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('margin_left') ? theme_get_setting('margin_left') : '30',
  ];

  $form['decorations']['margins_paddings']['margin']['margin_unit'] = [
    '#type' => 'textfield',
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('margin_unit') ? theme_get_setting('margin_unit') : '1',
  ];



  $form['decorations']['margins_paddings']['padding'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
    ],
  ];

  $form['decorations']['margins_paddings']['padding']['padding_top'] = [
    '#title' => t('Padding (Top, right, bottom, left)'),
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('padding_top') ? theme_get_setting('padding_top') : '30',
  ];

  $form['decorations']['margins_paddings']['padding']['padding_right'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('padding_right') ? theme_get_setting('padding_right') : '30',
  ];

  $form['decorations']['margins_paddings']['padding']['padding_bottom'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('padding_bottom') ? theme_get_setting('padding_bottom') : '30',
  ];

  $form['decorations']['margins_paddings']['padding']['padding_left'] = [
    '#type' => 'textfield',
    '#default_value' => theme_get_setting('padding_left') ? theme_get_setting('padding_left') : '30',
  ];

  $form['decorations']['margins_paddings']['padding']['padding_unit'] = [
    '#type' => 'textfield',
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('padding_unit') ? theme_get_setting('padding_unit') : '1',
  ];





 // section buttons


 $form['buttons'] = [
  '#type' => 'details',
  '#title' => t('Buttons'),
  '#summary' => t('Styling of buttons.'),
  '#group' => 'iq_theme',
];


$form['buttons']['default'] = [
  '#type' => 'details',
  '#title' => t('Default Button'),
];

$form['buttons']['default']['button_font_family'] = [
  '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>Main button styling</strong>',
  '#type' => 'select',
  '#title' => t('Font family'),
  '#options' => $arr_fonts,
  '#default_value' => theme_get_setting('button_font_family'),
];


$form['buttons']['default']['button_font_weight'] = [
  '#type' => 'select',
  '#options' => $arr_fontweights,
  '#title' => t('Font weight'),
  '#default_value' => theme_get_setting('button_font_weight'),
];

$form['buttons']['default']['button_font_style'] = [
  '#type' => 'select',
  '#options' => $arr_fontstyles,
  '#title' => t('Font style'),
  '#default_value' => theme_get_setting('button_font_style'),
];

$form['buttons']['default']['button_line_height'] = [
  '#type' => 'textfield',
  '#title' => t('Line height'),
  '#default_value' => theme_get_setting('button_line_height'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['button_font_size_holder'] = [
  '#type' => 'container',
  '#prefix' => '<div class="inline-input-holder">',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'separator'],
  ]
];

$form['buttons']['default']['button_font_size_holder']['button_font_size'] = [
  '#type' => 'textfield',
  '#title' => t('Font size'),
  '#default_value' => theme_get_setting('button_font_size'),
];

$form['buttons']['default']['button_font_size_holder']['button_font_size_unit'] = [
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_font_size_unit'),
];






$form['buttons']['default']['button_border_width_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
  ],
];

$form['buttons']['default']['button_border_width_holder']['button_border_width_top'] = [
  '#title' => t('Border (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_border_width_top'),
];

$form['buttons']['default']['button_border_width_holder']['button_border_width_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_border_width_right'),
];

$form['buttons']['default']['button_border_width_holder']['button_border_width_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_border_width_bottom'),
];

$form['buttons']['default']['button_border_width_holder']['button_border_width_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_border_width_left'),
];

$form['buttons']['default']['button_border_width_holder']['button_border_width_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_border_width_unit'),
];

$form['buttons']['default']['button_border_radius_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'separator'],
  ]
];

$form['buttons']['default']['button_border_radius_holder']['button_border_radius'] = [
  '#type' => 'textfield',
  '#title' => t('Border radius'),
  '#default_value' => theme_get_setting('button_border_radius'),
];

$form['buttons']['default']['button_border_radius_holder']['button_border_radius_unit'] = [
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_border_radius_unit'),
  '#suffix' => '</div>',
];



















$form['buttons']['default']['button_margin_holder'] = [
  '#type' => 'container',
  '#prefix' => '<div class="inline-input-holder">',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
  ],
];

$form['buttons']['default']['button_margin_holder']['button_margin_top'] = [
  '#title' => t('Margin (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_margin_top'),
];

$form['buttons']['default']['button_margin_holder']['button_margin_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_margin_right'),
];

$form['buttons']['default']['button_margin_holder']['button_margin_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_margin_bottom'),
];

$form['buttons']['default']['button_margin_holder']['button_margin_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_margin_left'),
];


$form['buttons']['default']['button_margin_holder']['button_margin_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_margin_unit'),
];


$form['buttons']['default']['button_padding_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
  ],
  '#suffix' => '</div>'
];

$form['buttons']['default']['button_padding_holder']['button_padding_top'] = [
  '#title' => t('Padding (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_padding_top'),
];

$form['buttons']['default']['button_padding_holder']['button_padding_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_padding_right'),
];

$form['buttons']['default']['button_padding_holder']['button_padding_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_padding_bottom'),
];

$form['buttons']['default']['button_padding_holder']['button_padding_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_padding_left'),
];


$form['buttons']['default']['button_padding_holder']['button_padding_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_padding_unit'),
];
















$form['buttons']['default']['standard'] = [
  '#type' => 'details',
  '#title' => t('Standard color settings'),
];

$form['buttons']['default']['standard']['button_font_color_standard'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_font_color_standard') ? theme_get_setting('button_font_color_standard') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Standard</strong>',
];

$form['buttons']['default']['standard']['button_font_opacity_standard'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_font_opacity_standard'),
  '#suffix' => '</div>'
];


$form['buttons']['default']['standard']['button_background_color_standard'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_background_color_standard') ? theme_get_setting('button_background_color_standard') : 'primary',
];

$form['buttons']['default']['standard']['button_background_opacity_standard'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_background_opacity_standard'),
];

$form['buttons']['default']['standard']['button_border_color_standard'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_border_color_standard') ? theme_get_setting('button_background_color_standard') : 'primary',
];

$form['buttons']['default']['standard']['button_border_opacity_standard'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_border_opacity_standard'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['standard']['button_font_color_hover'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_font_color_hover') ? theme_get_setting('button_font_color_hover') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Hover</strong>',
];

$form['buttons']['default']['standard']['button_font_opacity_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_font_opacity_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['standard']['button_background_color_hover'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_background_color_hover'),
];

$form['buttons']['default']['standard']['button_background_opacity_hover'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_background_opacity_hover'),
];

$form['buttons']['default']['standard']['button_border_color_hover'] = [
  '#type' => 'select',
  '#title' => t('Hover border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_border_color_hover'),
];

$form['buttons']['default']['standard']['button_border_opacity_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_border_opacity_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['standard']['button_font_color_active'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_font_color_active'),
  '#prefix' => '<div class="inline-input-holder"><strong>Active</strong>',
];

$form['buttons']['default']['standard']['button_font_opacity_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_font_opacity_active'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['standard']['button_background_color_active'] = [
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_background_color_active'),
  '#prefix' => '<div class="inline-input-holder separator">',
];

$form['buttons']['default']['standard']['button_background_opacity_active'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_background_opacity_active'),
];

$form['buttons']['default']['standard']['button_border_color_active'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_border_color_active'),
];

$form['buttons']['default']['standard']['button_border_opacity_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_border_opacity_active'),
  '#suffix' => '</div>'
];





$form['buttons']['default']['inverted'] = [
  '#type' => 'details',
  '#title' => t('Inverted color settings'),
];

$form['buttons']['default']['inverted']['button_font_color_inverted'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_font_color_inverted') ? theme_get_setting('button_font_color_inverted') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Standard</strong>',
];

$form['buttons']['default']['inverted']['button_font_opacity_inverted'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_font_opacity_inverted'),
  '#suffix' => '</div>'
];


$form['buttons']['default']['inverted']['button_background_color_inverted'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_background_color_inverted') ? theme_get_setting('button_background_color_inverted') : 'primary',
];

$form['buttons']['default']['inverted']['button_background_opacity_inverted'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_background_opacity_inverted'),
];

$form['buttons']['default']['inverted']['button_border_color_inverted'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_border_color_inverted') ? theme_get_setting('button_background_color_inverted') : 'primary',
];

$form['buttons']['default']['inverted']['button_border_opacity_inverted'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_border_opacity_inverted'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['inverted']['button_font_color_inverted_hover'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_font_color_inverted_hover') ? theme_get_setting('button_font_color_inverted_hover') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Hover</strong>',
];

$form['buttons']['default']['inverted']['button_font_opacity_inverted_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_font_opacity_inverted_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['inverted']['button_background_color_inverted_hover'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_background_color_inverted_hover'),
];

$form['buttons']['default']['inverted']['button_background_opacity_inverted_hover'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_background_opacity_inverted_hover'),
];

$form['buttons']['default']['inverted']['button_border_color_inverted_hover'] = [
  '#type' => 'select',
  '#title' => t('Hover border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_border_color_inverted_hover'),
];

$form['buttons']['default']['inverted']['button_border_opacity_inverted_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_border_opacity_inverted_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['inverted']['button_font_color_inverted_active'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_font_color_inverted_active'),
  '#prefix' => '<div class="inline-input-holder"><strong>Active</strong>',
];

$form['buttons']['default']['inverted']['button_font_opacity_inverted_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_font_opacity_inverted_active'),
  '#suffix' => '</div>'
];

$form['buttons']['default']['inverted']['button_background_color_inverted_active'] = [
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_background_color_inverted_active'),
  '#prefix' => '<div class="inline-input-holder separator">',
];

$form['buttons']['default']['inverted']['button_background_opacity_inverted_active'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_background_opacity_inverted_active'),
];

$form['buttons']['default']['inverted']['button_border_color_inverted_active'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_border_color_inverted_active'),
];

$form['buttons']['default']['inverted']['button_border_opacity_inverted_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_border_opacity_inverted_active'),
  '#suffix' => '</div>'
];


$form['buttons']['default']['button_title'] = [
  '#prefix' => '</div><div class="styling-preview">',
  '#suffix' => '</div></div>',
  '#type' => 'item',
  '#markup' => '<div class="preview-button standard">Standard</div><div class="preview-button hover">Hover</div><div class="preview-button active">Active</div><p>Buttons within text: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor <a href="#" class="preview-button inline">invidunt</a> ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. <br/><a href="#" class="preview-button inline">gubergren, no sea takimata sanctus est</a> <br/>Lorem ipsum dolor sit amet</p>
  <div class="preview-inverted"><div class="preview-button standard">Standard</div><div class="preview-button hover">Hover</div><div class="preview-button active">Active</div><p>Buttons within text: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor <a href="#" class="preview-button inline">invidunt</a> ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. <br/><a href="#" class="preview-button inline">gubergren, no sea takimata sanctus est</a> <br/>Lorem ipsum dolor sit amet</p></div>
  ',
];














// alternate button




$form['buttons']['alternate'] = [
  '#type' => 'details',
  '#title' => t('Alterante Button'),
];

$form['buttons']['alternate']['button_alternate_font_family'] = [
  '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>Main button styling</strong>',
  '#type' => 'select',
  '#title' => t('Font family'),
  '#options' => $arr_fonts,
  '#default_value' => theme_get_setting('button_alternate_font_family'),
];


$form['buttons']['alternate']['button_alternate_font_weight'] = [
  '#type' => 'select',
  '#options' => $arr_fontweights,
  '#title' => t('Font weight'),
  '#default_value' => theme_get_setting('button_alternate_font_weight'),
];

$form['buttons']['alternate']['button_alternate_font_style'] = [
  '#type' => 'select',
  '#options' => $arr_fontstyles,
  '#title' => t('Font style'),
  '#default_value' => theme_get_setting('button_alternate_font_style'),
];

$form['buttons']['alternate']['button_alternate_line_height'] = [
  '#type' => 'textfield',
  '#title' => t('Line height'),
  '#default_value' => theme_get_setting('button_alternate_line_height'),
  '#suffix' => '</div>'
];



$form['buttons']['alternate']['button_alternate_font_size_holder'] = [
  '#type' => 'container',
  '#prefix' => '<div class="inline-input-holder">',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'separator'],
  ]
];

$form['buttons']['alternate']['button_alternate_font_size_holder']['button_alternate_font_size'] = [
  '#type' => 'textfield',
  '#title' => t('Font size'),
  '#default_value' => theme_get_setting('button_alternate_font_size'),
];

$form['buttons']['alternate']['button_alternate_font_size_holder']['button_alternate_font_size_unit'] = [
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_alternate_font_size_unit'),
];



$form['buttons']['alternate']['button_alternate_border_width_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
  ],
];

$form['buttons']['alternate']['button_alternate_border_width_holder']['button_alternate_border_width_top'] = [
  '#title' => t('Border (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_border_width_top'),
];

$form['buttons']['alternate']['button_alternate_border_width_holder']['button_alternate_border_width_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_border_width_right'),
];

$form['buttons']['alternate']['button_alternate_border_width_holder']['button_alternate_border_width_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_border_width_bottom'),
];

$form['buttons']['alternate']['button_alternate_border_width_holder']['button_alternate_border_width_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_border_width_left'),
];

$form['buttons']['alternate']['button_alternate_border_width_holder']['button_alternate_border_width_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_alternate_border_width_unit'),
];

$form['buttons']['alternate']['button_alternate_border_radius_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'separator'],
  ]
];

$form['buttons']['alternate']['button_alternate_border_radius_holder']['button_alternate_border_radius'] = [
  '#type' => 'textfield',
  '#title' => t('Border radius'),
  '#default_value' => theme_get_setting('button_alternate_border_radius'),
];

$form['buttons']['alternate']['button_alternate_border_radius_holder']['button_alternate_border_radius_unit'] = [
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_alternate_border_radius_unit'),
  '#suffix' => '</div>',
];











$form['buttons']['alternate']['button_alternate_margin_holder'] = [
  '#type' => 'container',
  '#prefix' => '<div class="inline-input-holder">',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
  ],
];

$form['buttons']['alternate']['button_alternate_margin_holder']['button_alternate_margin_top'] = [
  '#title' => t('Margin (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_margin_top'),
];

$form['buttons']['alternate']['button_alternate_margin_holder']['button_alternate_margin_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_margin_right'),
];

$form['buttons']['alternate']['button_alternate_margin_holder']['button_alternate_margin_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_margin_bottom'),
];

$form['buttons']['alternate']['button_alternate_margin_holder']['button_alternate_margin_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_margin_left'),
];


$form['buttons']['alternate']['button_alternate_margin_holder']['button_alternate_margin_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_alternate_margin_unit'),
];


$form['buttons']['alternate']['button_alternate_padding_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
  ],
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['button_alternate_padding_holder']['button_alternate_padding_top'] = [
  '#title' => t('Padding (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_padding_top'),
];

$form['buttons']['alternate']['button_alternate_padding_holder']['button_alternate_padding_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_padding_right'),
];

$form['buttons']['alternate']['button_alternate_padding_holder']['button_alternate_padding_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_padding_bottom'),
];

$form['buttons']['alternate']['button_alternate_padding_holder']['button_alternate_padding_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('button_alternate_padding_left'),
];


$form['buttons']['alternate']['button_alternate_padding_holder']['button_alternate_padding_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('button_alternate_padding_unit'),
];










$form['buttons']['alternate']['standard'] = [
  '#type' => 'details',
  '#title' => t('Standard color settings'),
];

$form['buttons']['alternate']['standard']['button_alternate_font_color_standard'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_font_color_standard') ? theme_get_setting('button_alternate_font_color_standard') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Standard</strong>',
];

$form['buttons']['alternate']['standard']['button_alternate_font_opacity_standard'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_font_opacity_standard'),
  '#suffix' => '</div>'
];


$form['buttons']['alternate']['standard']['button_alternate_background_color_standard'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_background_color_standard') ? theme_get_setting('button_alternate_background_color_standard') : 'primary',
];

$form['buttons']['alternate']['standard']['button_alternate_background_opacity_standard'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_background_opacity_standard'),
];

$form['buttons']['alternate']['standard']['button_alternate_border_color_standard'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_border_color_standard') ? theme_get_setting('button_alternate_background_color_standard') : 'primary',
];

$form['buttons']['alternate']['standard']['button_alternate_border_opacity_standard'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_border_opacity_standard'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['standard']['button_alternate_font_color_hover'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_font_color_hover') ? theme_get_setting('button_alternate_font_color_hover') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Hover</strong>',
];

$form['buttons']['alternate']['standard']['button_alternate_font_opacity_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_font_opacity_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['standard']['button_alternate_background_color_hover'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_background_color_hover'),
];

$form['buttons']['alternate']['standard']['button_alternate_background_opacity_hover'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_background_opacity_hover'),
];

$form['buttons']['alternate']['standard']['button_alternate_border_color_hover'] = [
  '#type' => 'select',
  '#title' => t('Hover border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_border_color_hover'),
];

$form['buttons']['alternate']['standard']['button_alternate_border_opacity_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_border_opacity_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['standard']['button_alternate_font_color_active'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_font_color_active'),
  '#prefix' => '<div class="inline-input-holder"><strong>Active</strong>',
];

$form['buttons']['alternate']['standard']['button_alternate_font_opacity_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_font_opacity_active'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['standard']['button_alternate_background_color_active'] = [
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_background_color_active'),
  '#prefix' => '<div class="inline-input-holder separator">',
];

$form['buttons']['alternate']['standard']['button_alternate_background_opacity_active'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_background_opacity_active'),
];

$form['buttons']['alternate']['standard']['button_alternate_border_color_active'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_border_color_active'),
];

$form['buttons']['alternate']['standard']['button_alternate_border_opacity_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_border_opacity_active'),
  '#suffix' => '</div>'
];





$form['buttons']['alternate']['inverted'] = [
  '#type' => 'details',
  '#title' => t('Inverted color settings'),
];

$form['buttons']['alternate']['inverted']['button_alternate_font_color_inverted'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_font_color_inverted') ? theme_get_setting('button_alternate_font_color_inverted') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>inverted</strong>',
];

$form['buttons']['alternate']['inverted']['button_alternate_font_opacity_inverted'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_font_opacity_inverted'),
  '#suffix' => '</div>'
];


$form['buttons']['alternate']['inverted']['button_alternate_background_color_inverted'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_background_color_inverted') ? theme_get_setting('button_alternate_background_color_inverted') : 'primary',
];

$form['buttons']['alternate']['inverted']['button_alternate_background_opacity_inverted'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_background_opacity_inverted'),
];

$form['buttons']['alternate']['inverted']['button_alternate_border_color_inverted'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_border_color_inverted') ? theme_get_setting('button_alternate_background_color_inverted') : 'primary',
];

$form['buttons']['alternate']['inverted']['button_alternate_border_opacity_inverted'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_border_opacity_inverted'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['inverted']['button_alternate_font_color_inverted_hover'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_font_color_inverted_hover') ? theme_get_setting('button_alternate_font_color_inverted_hover') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Hover</strong>',
];

$form['buttons']['alternate']['inverted']['button_alternate_font_opacity_inverted_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_font_opacity_inverted_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['inverted']['button_alternate_background_color_inverted_hover'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_background_color_inverted_hover'),
];

$form['buttons']['alternate']['inverted']['button_alternate_background_opacity_inverted_hover'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_background_opacity_inverted_hover'),
];

$form['buttons']['alternate']['inverted']['button_alternate_border_color_inverted_hover'] = [
  '#type' => 'select',
  '#title' => t('Hover border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_border_color_inverted_hover'),
];

$form['buttons']['alternate']['inverted']['button_alternate_border_opacity_inverted_hover'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_border_opacity_inverted_hover'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['inverted']['button_alternate_font_color_inverted_active'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_font_color_inverted_active'),
  '#prefix' => '<div class="inline-input-holder"><strong>Active</strong>',
];

$form['buttons']['alternate']['inverted']['button_alternate_font_opacity_inverted_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_font_opacity_inverted_active'),
  '#suffix' => '</div>'
];

$form['buttons']['alternate']['inverted']['button_alternate_background_color_inverted_active'] = [
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_background_color_inverted_active'),
  '#prefix' => '<div class="inline-input-holder separator">',
];

$form['buttons']['alternate']['inverted']['button_alternate_background_opacity_inverted_active'] = [
  '#type' => 'textfield',
  '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_background_opacity_inverted_active'),
];

$form['buttons']['alternate']['inverted']['button_alternate_border_color_inverted_active'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('button_alternate_border_color_inverted_active'),
];

$form['buttons']['alternate']['inverted']['button_alternate_border_opacity_inverted_active'] = [
  '#type' => 'textfield',
  // '#attributes' => [
  //   'min' => 0,
  //   'max' => 1,
  //   'step' => 0.01,
  // ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('button_alternate_border_opacity_inverted_active'),
  '#suffix' => '</div>'
];


$form['buttons']['alternate']['button_alternate_title'] = [
  '#prefix' => '</div><div class="styling-preview button-alternate">',
  '#suffix' => '</div></div>',
  '#type' => 'item',
  '#markup' => '<div class="preview-button  standard">Standard</div><div class="preview-button hover">Hover</div><div class="preview-button active">Active</div><p>Buttons within text: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor <a href="#" class="preview-button inline">invidunt</a> ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. <br/><a href="#" class="preview-button inline">gubergren, no sea takimata sanctus est</a> <br/>Lorem ipsum dolor sit amet</p>
  <div class="preview-inverted"><div class="preview-button standard">Standard</div><div class="preview-button hover">Hover</div><div class="preview-button active">Active</div><p>Buttons within text: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor <a href="#" class="preview-button inline">invidunt</a> ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. <br/><a href="#" class="preview-button inline">gubergren, no sea takimata sanctus est</a> <br/>Lorem ipsum dolor sit amet</p></div>
  ',
];



























  // section patterns

  $form['patterns'] = [
    '#type' => 'details',
    '#title' => t('Patterns'),
    '#summary' => t('Styling of patterns.'),
    '#group' => 'iq_theme',
  ];



  $form['patterns']['slider'] = [
    '#type' => 'details',
    '#title' => t('Slider'),
  ];

  $form['patterns']['slider']['slider_arrow_size_holder'] = [
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Arrows</strong>',
    '#type' => 'container',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'separator'],
    ]
  ];

  $form['patterns']['slider']['slider_arrow_size_holder']['slider_arrow_size'] = [
    '#type' => 'textfield',
    '#title' => t('Size'),
    '#default_value' => theme_get_setting('slider_arrow_size') ? theme_get_setting('slider_arrow_size') : '1',
  ];

  $form['patterns']['slider']['slider_arrow_size_holder']['slider_arrow_size_unit'] = [
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('slider_arrow_size_unit') ? theme_get_setting('slider_arrow_size_unit') : 'rem',
  ];

  $form['patterns']['slider']['slider_arrow_color'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('slider_arrow_color') ? theme_get_setting('slider_arrow_color') : 'grey3',
  ];

  $form['patterns']['slider']['slider_arrow_opacity'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => [ 'separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('slider_arrow_opacity'),
  ];

  $form['patterns']['slider']['slider_arrow_backgroundcolor'] = [
    '#type' => 'select',
    '#title' => t('Background color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('slider_arrow_backgroundcolor') ? theme_get_setting('slider_arrow_backgroundcolor') : 'white',
  ];

  $form['patterns']['slider']['slider_arrow_background_opacity'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('slider_arrow_background_opacity'),
    '#suffix' => '</div>'
  ];




  $form['patterns']['slider']['slider_dot_size_holder'] = [
    '#type' => 'container',
    '#prefix' => '<div class="inline-input-holder "><strong>Dots</strong>',
    '#attributes' => [
      'class' => ['container-inline', 'unit-combo-field', 'separator'],
    ]
  ];

  $form['patterns']['slider']['slider_dot_size_holder']['slider_dot_size'] = [
    '#type' => 'textfield',
    '#title' => t('Size'),
    '#default_value' => theme_get_setting('slider_dot_size') ? theme_get_setting('slider_dot_size') : '1',
  ];

  $form['patterns']['slider']['slider_dot_size_holder']['slider_dot_size_unit'] = [
    '#type' => 'select',
    '#options' => $arr_units,
    '#default_value' => theme_get_setting('slider_dot_size_unit') ? theme_get_setting('slider_dot_size_unit') : 'rem',
  ];

  $form['patterns']['slider']['slider_dot_color'] = [
    '#type' => 'select',
    '#title' => t('Colo standard'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('slider_dot_color') ? theme_get_setting('slider_dot_color') : 'grey3',
  ];

  $form['patterns']['slider']['slider_dot_opacity'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => [ 'separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('slider_dot_opacity'),
  ];

  $form['patterns']['slider']['slider_dot_color_active'] = [
    '#type' => 'select',
    '#title' => t('Color active'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('slider_dot_color_active') ? theme_get_setting('slider_dot_color_active') : 'grey1',
  ];

  $form['patterns']['slider']['slider_dot_opacity_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('slider_dot_opacity_active'),
    '#suffix' => '</div></div></div>'
  ];



  $form['patterns']['quote'] = [
    '#type' => 'details',
    '#title' => t('Quote'),
  ];

  $form['patterns']['quote']['quote_highlight_color'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('quote_highlight_color') ? theme_get_setting('quote_highlight_color') : 'grey3',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Highlights (quote marks / lines)</strong>',
  ];

  $form['patterns']['quote']['quote_highlight_opacity'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('quote_highlight_opacity'),
    '#suffix' => '</div></div></div>'
  ];



  $form['patterns']['icons'] = [
    '#type' => 'details',
    '#title' => t('Icons'),
  ];


  $form['patterns']['icons']['default'] = [
    '#type' => 'details',
    '#title' => t('Default icon'),
  ];



  $form['patterns']['icons']['default']['color_icons'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons') ? theme_get_setting('color_icons') : 'primary',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Standard</strong>',
  ];

  $form['patterns']['icons']['default']['opacity_icons'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['default']['color_icons_hover'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_hover') ? theme_get_setting('color_icons_hover') : 'primary',
    '#prefix' => '<div class="inline-input-holder "><strong>Hover</strong>',
  ];

  $form['patterns']['icons']['default']['opacity_icons_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_hover'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['default']['color_icons_active'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_active') ? theme_get_setting('color_icons_active') : 'primary',
    '#prefix' => '<div class="inline-input-holder separator"><strong>Active</strong>',
  ];

  $form['patterns']['icons']['default']['opacity_icons_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_active'),
    '#suffix' => '</div>'
  ];







  $form['patterns']['icons']['default']['color_icons_inverted'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_inverted') ? theme_get_setting('color_icons_inverted') : 'primary',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Inverted</strong>',
  ];

  $form['patterns']['icons']['default']['opacity_icons_inverted'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_inverted'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['default']['color_icons_inverted_hover'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_inverted_hover') ? theme_get_setting('color_icons_inverted_hover') : 'primary',
    '#prefix' => '<div class="inline-input-holder "><strong>Inverted hover</strong>',
  ];

  $form['patterns']['icons']['default']['opacity_icons_inverted_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_inverted_hover'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['default']['color_icons_inverted_active'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_inverted_active') ? theme_get_setting('color_icons_inverted_active') : 'primary',
    '#prefix' => '<div class="inline-input-holder"><strong>Inverted active</strong>',
  ];

  $form['patterns']['icons']['default']['opacity_icons_inverted_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_inverted_active'),
    '#suffix' => '</div></div></div>'
  ];







  $form['patterns']['icons']['alternate'] = [
    '#type' => 'details',
    '#title' => t('Alternate icon'),
  ];




  $form['patterns']['icons']['alternate']['color_icons_alternate'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_alternate') ? theme_get_setting('color_icons_alternate') : 'primary',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Standard</strong>',
  ];

  $form['patterns']['icons']['alternate']['opacity_icons_alternate'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_alternate'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['alternate']['color_icons_alternate_hover'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_alternate_hover') ? theme_get_setting('color_icons_alternate_hover') : 'primary',
    '#prefix' => '<div class="inline-input-holder "><strong>Hover</strong>',
  ];

  $form['patterns']['icons']['alternate']['opacity_icons_alternate_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_alternate_hover'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['alternate']['color_icons_alternate_active'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_alternate_active') ? theme_get_setting('color_icons_alternate_active') : 'primary',
    '#prefix' => '<div class="inline-input-holder separator"><strong>Active</strong>',
  ];

  $form['patterns']['icons']['alternate']['opacity_icons_alternate_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_alternate_active'),
    '#suffix' => '</div>'
  ];







  $form['patterns']['icons']['alternate']['color_icons_alternate_inverted'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_alternate_inverted') ? theme_get_setting('color_icons_alternate_inverted') : 'primary',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Inverted</strong>',
  ];

  $form['patterns']['icons']['alternate']['opacity_icons_alternate_inverted'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_alternate_inverted'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['alternate']['color_icons_alternate_inverted_hover'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_alternate_inverted_hover') ? theme_get_setting('color_icons_alternate_inverted_hover') : 'primary',
    '#prefix' => '<div class="inline-input-holder "><strong>Inverted hover</strong>',
  ];

  $form['patterns']['icons']['alternate']['opacity_icons_alternate_inverted_hover'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_alternate_inverted_hover'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['icons']['alternate']['color_icons_alternate_inverted_active'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('color_icons_alternate_inverted_active') ? theme_get_setting('color_icons_alternate_inverted_active') : 'primary',
    '#prefix' => '<div class="inline-input-holder"><strong>Inverted active</strong>',
  ];

  $form['patterns']['icons']['alternate']['opacity_icons_alternate_inverted_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('opacity_icons_alternate_inverted_active'),
    '#suffix' => '</div></div></div>'
  ];

















  $form['patterns']['social'] = [
    '#type' => 'details',
    '#title' => t('Social'),
  ];

  $form['patterns']['social']['social_icon_color'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('social_icon_color') ? theme_get_setting('social_icon_color') : 'grey3',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Social icons</strong>',
  ];

  $form['patterns']['social']['social_icon_opacity'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('social_icon_opacity'),
    '#suffix' => '</div></div></div>'
  ];



  $form['patterns']['tabs'] = [
    '#type' => 'details',
    '#title' => t('Tabbed content'),
  ];

  $form['patterns']['tabs']['tab_color'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('tab_color') ? theme_get_setting('tab_color') : 'primary',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Tab standard</strong>',
  ];


  $form['patterns']['tabs']['tab_opacity'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => [ 'separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('tab_opacity'),
  ];

  $form['patterns']['tabs']['tab_font_color'] = [
    '#type' => 'select',
    '#title' => t('Font color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('tab_font_color') ? theme_get_setting('tab_font_color') : 'grey1',
  ];

  $form['patterns']['tabs']['tab_font_opacity'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('tab_font_opacity'),
    '#suffix' => '</div>'
  ];





  $form['patterns']['tabs']['tab_color_active'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('tab_color_active') ? theme_get_setting('tab_color_active') : 'grey3',
    '#prefix' => '<div class="inline-input-holder "><strong>Tab Active</strong>',
  ];

  $form['patterns']['tabs']['tab_opacity_active'] = [
    '#type' => 'textfield',
    '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
      'class' => [ 'separator'],
    ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('tab_opacity_active'),
  ];

  $form['patterns']['tabs']['tab_font_color_active'] = [
    '#type' => 'select',
    '#title' => t('Tab font color active'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('tab_font_color_active') ? theme_get_setting('tab_font_color_active') : 'grey1',
  ];

  $form['patterns']['tabs']['tab_font_opacity_active'] = [
    '#type' => 'textfield',
    // '#attributes' => [
    //   'min' => 0,
    //   'max' => 1,
    //   'step' => 0.01,
    // ],
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('tab_font_opacity_active'),
    '#suffix' => '</div></div></div>'
  ];




  $form['patterns']['toggler'] = [
    '#type' => 'details',
    '#title' => t('Toggler'),
  ];

  $form['patterns']['toggler']['toggler_color'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('toggler_color') ? theme_get_setting('toggler_color') : 'grey3',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Standard</strong>',
  ];

  $form['patterns']['toggler']['toggler_opacity'] = [
    '#type' => 'textfield',
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('toggler_opacity'),
    '#suffix' => '</div>'
  ];


  $form['patterns']['toggler']['toggler_color_hover'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('toggler_color_hover') ? theme_get_setting('toggler_color_hover') : 'grey3',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Hover</strong>',
  ];

  $form['patterns']['toggler']['toggler_opacity_hover'] = [
    '#type' => 'textfield',
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('toggler_opacity_hover'),
    '#suffix' => '</div>'
  ];

  $form['patterns']['toggler']['toggler_color_active'] = [
    '#type' => 'select',
    '#title' => t('Color'),
    '#options' => $arr_colors,
    '#default_value' => theme_get_setting('toggler_color_active') ? theme_get_setting('toggler_color_active') : 'grey3',
    '#prefix' => '<div class="styling-row"><div class="styling-input full"><div class="inline-input-holder "><strong>Active</strong>',
  ];

  $form['patterns']['toggler']['toggler_opacity_active'] = [
    '#type' => 'textfield',
    '#title' => t('Opacity'),
    '#default_value' => theme_get_setting('toggler_opacity_active'),
    '#suffix' => '</div></div></div>'
  ];
















 // section buttons


 $form['patterns']['anchornavigation'] = [
  '#type' => 'details',
  '#title' => t('Anchor navigation'),
];

$form['patterns']['anchornavigation']['anchornavigation_font_family'] = [
  '#prefix' => '<div class="styling-row"><div class="styling-input"><div class="inline-input-holder"><strong>Main styling</strong>',
  '#type' => 'select',
  '#title' => t('Font family'),
  '#options' => $arr_fonts,
  '#default_value' => theme_get_setting('anchornavigation_font_family'),
];

$form['patterns']['anchornavigation']['anchornavigation_font_weight'] = [
  '#type' => 'select',
  '#options' => $arr_fontweights,
  '#title' => t('Font weight'),
  '#default_value' => theme_get_setting('anchornavigation_font_weight'),
];


$form['patterns']['anchornavigation']['anchornavigation_font_style'] = [
  '#type' => 'select',
  '#options' => $arr_fontstyles,
  '#title' => t('Font style'),
  '#default_value' => theme_get_setting('anchornavigation_font_style'),
];

$form['patterns']['anchornavigation']['anchornavigation_line_height'] = [
  '#type' => 'textfield',
  '#title' => t('Line height'),
  '#default_value' => theme_get_setting('anchornavigation_line_height'),
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_font_size_holder'] = [
  '#type' => 'container',
  '#prefix' => '<div class="inline-input-holder">',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'separator'],
  ]
];

$form['patterns']['anchornavigation']['anchornavigation_font_size_holder']['anchornavigation_font_size'] = [
  '#type' => 'textfield',
  '#title' => t('Font size'),
  '#default_value' => theme_get_setting('anchornavigation_font_size'),
];

$form['patterns']['anchornavigation']['anchornavigation_font_size_holder']['anchornavigation_font_size_unit'] = [
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('anchornavigation_font_size_unit'),
];


$form['patterns']['anchornavigation']['anchornavigation_margin_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule', 'separator'],
  ],
];

$form['patterns']['anchornavigation']['anchornavigation_margin_holder']['anchornavigation_margin_top'] = [
  '#title' => t('Margin (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_margin_top'),
];

$form['patterns']['anchornavigation']['anchornavigation_margin_holder']['anchornavigation_margin_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_margin_right'),
];

$form['patterns']['anchornavigation']['anchornavigation_margin_holder']['anchornavigation_margin_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_margin_bottom'),
];

$form['patterns']['anchornavigation']['anchornavigation_margin_holder']['anchornavigation_margin_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_margin_left'),
];


$form['patterns']['anchornavigation']['anchornavigation_margin_holder']['anchornavigation_margin_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('anchornavigation_margin_unit'),
];


$form['patterns']['anchornavigation']['anchornavigation_padding_holder'] = [
  '#type' => 'container',
  '#attributes' => [
    'class' => ['container-inline', 'unit-combo-field', 'multi-valule'],
  ],
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_padding_holder']['anchornavigation_padding_top'] = [
  '#title' => t('Padding (top, right, bottom, left)'),
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_padding_top'),
];

$form['patterns']['anchornavigation']['anchornavigation_padding_holder']['anchornavigation_padding_right'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_padding_right'),
];

$form['patterns']['anchornavigation']['anchornavigation_padding_holder']['anchornavigation_padding_bottom'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_padding_bottom'),
];

$form['patterns']['anchornavigation']['anchornavigation_padding_holder']['anchornavigation_padding_left'] = [
  '#type' => 'textfield',
  '#default_value' => theme_get_setting('anchornavigation_padding_left'),
];

$form['patterns']['anchornavigation']['anchornavigation_padding_holder']['anchornavigation_padding_unit'] = [
  '#type' => 'textfield',
  '#type' => 'select',
  '#options' => $arr_units,
  '#default_value' => theme_get_setting('anchornavigation_padding_unit'),
];

$form['patterns']['anchornavigation']['anchornavigation_wrapper_background_color'] = [
  '#type' => 'select',
  '#title' => t('Wrapper background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_wrapper_background_color') ? theme_get_setting('anchornavigation_wrapper_background_color') : 'white',
  '#prefix' => '<div class="inline-input-holder separator"><strong>Color settings</strong>',
];

$form['patterns']['anchornavigation']['anchornavigation_wrapper_background_opacity'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_wrapper_background_opacity'),
  '#suffix' => '</div>'
];



$form['patterns']['anchornavigation']['anchornavigation_font_color_standard'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_font_color_standard') ? theme_get_setting('anchornavigation_font_color_standard') : 'grey1',
  '#prefix' => '<div class="inline-input-holder"><strong>Standard</strong>',
];

$form['patterns']['anchornavigation']['anchornavigation_font_opacity_standard'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_font_opacity_standard'),
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_background_color_standard'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_background_color_standard') ? theme_get_setting('anchornavigation_background_color_standard') : 'white',
];

$form['patterns']['anchornavigation']['anchornavigation_background_opacity_standard'] = [
  '#type' => 'textfield',
  '#attributes' => [
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_background_opacity_standard'),
];

$form['patterns']['anchornavigation']['anchornavigation_border_color_standard'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_border_color_standard') ? theme_get_setting('anchornavigation_background_color_standard') : 'white',
];

$form['patterns']['anchornavigation']['anchornavigation_border_opacity_standard'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_border_opacity_standard'),
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_font_color_hover'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_font_color_hover') ? theme_get_setting('anchornavigation_font_color_hover') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Hover</strong>',
];

$form['patterns']['anchornavigation']['anchornavigation_font_opacity_hover'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_font_opacity_hover'),
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_background_color_hover'] = [
  '#prefix' => '<div class="inline-input-holder separator">',
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_background_color_hover') ? theme_get_setting('anchornavigation_background_color_hover') : 'primary',
];

$form['patterns']['anchornavigation']['anchornavigation_background_opacity_hover'] = [
  '#type' => 'textfield',
  '#attributes' => [
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_background_opacity_hover'),
];

$form['patterns']['anchornavigation']['anchornavigation_border_color_hover'] = [
  '#type' => 'select',
  '#title' => t('Hover border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_border_color_hover') ? theme_get_setting('anchornavigation_border_color_hover') : 'primary',
];

$form['patterns']['anchornavigation']['anchornavigation_border_opacity_hover'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_border_opacity_hover'),
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_font_color_active'] = [
  '#type' => 'select',
  '#title' => t('Font color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_font_color_active') ? theme_get_setting('anchornavigation_font_color_active') : 'white',
  '#prefix' => '<div class="inline-input-holder"><strong>Active</strong>',
];

$form['patterns']['anchornavigation']['anchornavigation_font_opacity_active'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_font_opacity_active'),
  '#suffix' => '</div>'
];

$form['patterns']['anchornavigation']['anchornavigation_background_color_active'] = [
  '#type' => 'select',
  '#title' => t('Background color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_background_color_active') ? theme_get_setting('anchornavigation_background_color_active') : 'primary',
  '#prefix' => '<div class="inline-input-holder separator">',
];

$form['patterns']['anchornavigation']['anchornavigation_background_opacity_active'] = [
  '#type' => 'textfield',
  '#attributes' => [
    'class' => ['separator'],
  ],
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_background_opacity_active'),
];

$form['patterns']['anchornavigation']['anchornavigation_border_color_active'] = [
  '#type' => 'select',
  '#title' => t('Border color'),
  '#options' => $arr_colors,
  '#default_value' => theme_get_setting('anchornavigation_border_color_active'),
];

$form['patterns']['anchornavigation']['anchornavigation_border_opacity_active'] = [
  '#type' => 'textfield',
  '#title' => t('Opacity'),
  '#default_value' => theme_get_setting('anchornavigation_border_opacity_active'),
  '#suffix' => '</div>'
];


















































  $form['#submit'][] = 'iq_barrio_form_system_theme_settings_submit';
}

/**
 * Implements hook_form_system_theme_settings_submit().
 */
function iq_barrio_form_system_theme_settings_submit($form, FormStateInterface &$form_state)
{
  $title_font = $form_state->getValue('title_font');
  $content_font = $form_state->getValue('content_font');

  if (strpos(strtolower($form_state->getValue('title_font')), 'regular')) {
    $title_font = trim(strstr($form_state->getValue('title_font'), 'regular', true));
  }

  if (strpos(strtolower($form_state->getValue('content_font')), 'regular')) {
    $content_font = trim(strstr($form_state->getValue('content_font'), 'regular', true));
  }

  $arrKeywords = [
    'color_grey1' =>  $form_state->getValue('color_grey1'),
    'color_grey2' =>  $form_state->getValue('color_grey2'),
    'color_grey3' =>  $form_state->getValue('color_grey3'),
    'color_grey4' =>  $form_state->getValue('color_grey4'),
    'color_grey5' =>  $form_state->getValue('color_grey5'),
    'color_primary' =>  $form_state->getValue('color_primary'),
    'color_secondary' =>  $form_state->getValue('color_secondary'),
    'color_tertiary' =>  $form_state->getValue('color_tertiary'),
    'color_quaternary' =>  $form_state->getValue('color_quaternary'),

    'color_icons' => $form_state->getValue('color_icons'),
    'opacity_icons' => $form_state->getValue('opacity_icons'),

    'color_icons_hover' => $form_state->getValue('color_icons_hover'),
    'opacity_icons_hover' => $form_state->getValue('opacity_icons_hover'),

    'color_icons_active' => $form_state->getValue('color_icons_active'),
    'opacity_icons_active' => $form_state->getValue('opacity_icons_active'),

    'color_icons_inverted' => $form_state->getValue('color_icons_inverted'),
    'opacity_icons_inverted' => $form_state->getValue('opacity_icons_inverted'),

    'color_icons_inverted_hover' => $form_state->getValue('color_icons_inverted_hover'),
    'opacity_icons_inverted_hover' => $form_state->getValue('opacity_icons_inverted_hover'),

    'color_icons_inverted_active' => $form_state->getValue('color_icons_inverted_active'),
    'opacity_icons_inverted_active' => $form_state->getValue('opacity_icons_inverted_active'),


    'color_icons_alternate' => $form_state->getValue('color_icons_alternate'),
    'opacity_icons_alternate' => $form_state->getValue('opacity_icons_alternate'),

    'color_icons_alternate_hover' => $form_state->getValue('color_icons_alternate_hover'),
    'opacity_icons_alternate_hover' => $form_state->getValue('opacity_icons_alternate_hover'),

    'color_icons_alternate_active' => $form_state->getValue('color_icons_alternate_active'),
    'opacity_icons_alternate_active' => $form_state->getValue('opacity_icons_alternate_active'),


    'color_icons_alternate_inverted' => $form_state->getValue('color_icons_alternate_inverted'),
    'opacity_icons_alternate_inverted' => $form_state->getValue('opacity_icons_alternate_inverted'),

    'color_icons_alternate_inverted_hover' => $form_state->getValue('color_icons_alternate_inverted_hover'),
    'opacity_icons_alternate_inverted_hover' => $form_state->getValue('opacity_icons_alternate_inverted_hover'),

    'color_icons_alternate_inverted_active' => $form_state->getValue('color_icons_alternate_inverted_active'),
    'opacity_icons_alternate_inverted_active' => $form_state->getValue('opacity_icons_alternate_inverted_active'),



    'color_page_background' => $form_state->getValue('color_page_background'),
    'opacity_color_page_background' => $form_state->getValue('opacity_color_page_background'),

    'color_page_background_header' => $form_state->getValue('color_page_background_header'),
    'opacity_color_page_background_header' => $form_state->getValue('opacity_color_page_background_header'),

    'color_page_font_header' => $form_state->getValue('color_page_font_header'),
    'opacity_color_page_font_header' => $form_state->getValue('opacity_color_page_font_header'),

    'color_page_background_meta_header' => $form_state->getValue('color_page_background_meta_header'),
    'opacity_color_page_background_meta_header' => $form_state->getValue('opacity_color_page_background_meta_header'),

    'color_page_font_meta_header' => $form_state->getValue('color_page_font_meta_header'),
    'opacity_color_page_font_meta_header' => $form_state->getValue('opacity_color_page_font_meta_header'),

    'color_page_background_footer' => $form_state->getValue('color_page_background_footer'),
    'opacity_color_page_background_footer' => $form_state->getValue('opacity_color_page_background_footer'),


    'color_page_background_navbar' => $form_state->getValue('color_page_background_navbar'),
    'opacity_page_background_navbar' => $form_state->getValue('opacity_page_background_navbar'),

    'color_page_font_navbar' => $form_state->getValue('color_page_font_navbar'),
    'opacity_page_font_navbar' => $form_state->getValue('opacity_page_font_navbar'),

    'color_page_background_navbar_hover' => $form_state->getValue('color_page_background_navbar_hover'),
    'opacity_page_background_navbar_hover' => $form_state->getValue('opacity_page_background_navbar_hover'),

    'color_page_font_navbar_hover' => $form_state->getValue('color_page_font_navbar_hover'),
    'opacity_page_font_navbar_hover' => $form_state->getValue('opacity_page_font_navbar_hover'),

    'color_page_background_navbar_active' => $form_state->getValue('color_page_background_navbar_active'),
    'opacity_page_background_navbar_active' => $form_state->getValue('opacity_page_background_navbar_active'),

    'color_page_font_navbar_active' => $form_state->getValue('color_page_font_navbar_active'),
    'opacity_page_font_navbar_active' => $form_state->getValue('opacity_page_font_navbar_active'),

    'navi_main_font_family' => $form_state->getValue('navi_main_font_family'),
    'navi_main_font_weight' => $form_state->getValue('navi_main_font_weight'),
    'navi_main_font_style' => $form_state->getValue('navi_main_font_style'),
    'navi_main_line_height' => $form_state->getValue('navi_main_line_height'),
    'navi_main_font_size' => $form_state->getValue('navi_main_font_size'),
    'navi_main_font_size_unit' => $form_state->getValue('navi_main_font_size_unit'),
    'navi_main_margin_top' => $form_state->getValue('navi_main_margin_top'),
    'navi_main_margin_left_right' => $form_state->getValue('navi_main_margin_left_right'),
    'navi_main_margin_bottom' => $form_state->getValue('navi_main_margin_bottom'),
    'navi_main_margin_unit' => $form_state->getValue('navi_main_margin_unit'),
    'navi_main_padding_top' => $form_state->getValue('navi_main_padding_top'),
    'navi_main_padding_left_right' => $form_state->getValue('navi_main_padding_left_right'),
    'navi_main_padding_bottom' => $form_state->getValue('navi_main_padding_bottom'),
    'navi_main_padding_unit' => $form_state->getValue('navi_main_padding_unit'),

    'color_page_font_nav_dropdown' => $form_state->getValue('color_page_font_nav_dropdown'),
    'opacity_page_font_nav_dropdown' => $form_state->getValue('opacity_page_font_nav_dropdown'),

    'color_page_background_nav_dropdown' => $form_state->getValue('color_page_background_nav_dropdown'),
    'opacity_page_background_nav_dropdown' => $form_state->getValue('opacity_page_background_nav_dropdown'),

    'color_page_font_nav_dropdown_hover' => $form_state->getValue('color_page_font_nav_dropdown_hover'),
    'opacity_page_font_nav_dropdown_hover' => $form_state->getValue('opacity_page_font_nav_dropdown_hover'),

    'color_page_background_nav_dropdown_hover' => $form_state->getValue('color_page_background_nav_dropdown_hover'),
    'opacity_page_background_nav_dropdown_hover' => $form_state->getValue('opacity_page_background_nav_dropdown_hover'),

    'color_page_font_nav_dropdown_active' => $form_state->getValue('color_page_font_nav_dropdown_active'),
    'opacity_page_font_nav_dropdown_active' => $form_state->getValue('opacity_page_font_nav_dropdown_active'),

    'color_page_background_nav_dropdown_active' => $form_state->getValue('color_page_background_nav_dropdown_active'),
    'opacity_page_background_nav_dropdown_active' => $form_state->getValue('opacity_page_background_nav_dropdown_active'),

    'color_page_font_footer' => $form_state->getValue('color_page_font_footer'),
    'opacity_color_page_font_footer' => $form_state->getValue('opacity_color_page_font_footer'),

    'color_page_background_elements' => $form_state->getValue('color_page_background_elements'),
    'opacity_color_page_background_elements' => $form_state->getValue('opacity_color_page_background_elements'),

    'color_text_inverted' => $form_state->getValue('color_text_inverted'),
    'opacity_text_inverted' => $form_state->getValue('opacity_text_inverted'),

    'color_page_background_nav_mobile' => $form_state->getValue('color_page_background_nav_mobile'),
    'opacity_page_background_nav_mobile' => $form_state->getValue('opacity_page_background_nav_mobile'),

    'color_page_font_nav_mobile' => $form_state->getValue('color_page_font_nav_mobile'),
    'opacity_page_font_nav_mobile' => $form_state->getValue('opacity_page_font_nav_mobile'),

    'color_page_font_nav_mobile_hover' => $form_state->getValue('color_page_font_nav_mobile_hover'),
    'opacity_page_font_nav_mobile_hover' => $form_state->getValue('opacity_page_font_nav_mobile_hover'),

    'color_page_font_nav_sidebar' => $form_state->getValue('color_page_font_nav_sidebar'),
    'opacity_page_font_nav_sidebar' => $form_state->getValue('opacity_page_font_nav_sidebar'),

    'color_page_font_nav_sidebar_hover' => $form_state->getValue('color_page_font_nav_sidebar_hover'),
    'opacity_page_font_nav_sidebar_hover' => $form_state->getValue('opacity_page_font_nav_sidebar_hover'),


    'h1_font_family' => $form_state->getValue('h1_font_family'),
    'h1_color' => $form_state->getValue('h1_color'),
    'h1_opacity' => $form_state->getValue('h1_opacity'),
    'h1_font_size' => $form_state->getValue('h1_font_size'),
    'h1_font_size_unit' => $form_state->getValue('h1_font_size_unit'),
    'h1_font_size_min' => $form_state->getValue('h1_font_size_min'),
    'h1_line_height' => $form_state->getValue('h1_line_height'),
    'h1_font_weight' => $form_state->getValue('h1_font_weight'),
    'h1_font_style' => $form_state->getValue('h1_font_style'),
    'h1_margin_top' => $form_state->getValue('h1_margin_top'),
    'h1_margin_bottom' => $form_state->getValue('h1_margin_bottom'),
    'h1_margin_unit' => $form_state->getValue('h1_margin_unit'),

    'h2_font_family' => $form_state->getValue('h2_font_family'),
    'h2_color' => $form_state->getValue('h2_color'),
    'h2_opacity' => $form_state->getValue('h2_opacity'),
    'h2_font_size' => $form_state->getValue('h2_font_size'),
    'h2_font_size_unit' => $form_state->getValue('h2_font_size_unit'),
    'h2_font_size_min' => $form_state->getValue('h2_font_size_min'),
    'h2_line_height' => $form_state->getValue('h2_line_height'),
    'h2_font_weight' => $form_state->getValue('h2_font_weight'),
    'h2_font_style' => $form_state->getValue('h2_font_style'),
    'h2_margin_top' => $form_state->getValue('h2_margin_top'),
    'h2_margin_bottom' => $form_state->getValue('h2_margin_bottom'),
    'h2_margin_unit' => $form_state->getValue('h2_margin_unit'),

    'h3_font_family' => $form_state->getValue('h3_font_family'),
    'h3_color' => $form_state->getValue('h3_color'),
    'h3_opacity' => $form_state->getValue('h3_opacity'),
    'h3_font_size' => $form_state->getValue('h3_font_size'),
    'h3_font_size_unit' => $form_state->getValue('h3_font_size_unit'),
    'h3_font_size_min' => $form_state->getValue('h3_font_size_min'),
    'h3_line_height' => $form_state->getValue('h3_line_height'),
    'h3_font_weight' => $form_state->getValue('h3_font_weight'),
    'h3_font_style' => $form_state->getValue('h3_font_style'),
    'h3_margin_top' => $form_state->getValue('h3_margin_top'),
    'h3_margin_bottom' => $form_state->getValue('h3_margin_bottom'),
    'h3_margin_unit' => $form_state->getValue('h3_margin_unit'),

    'h4_font_family' => $form_state->getValue('h4_font_family'),
    'h4_color' => $form_state->getValue('h4_color'),
    'h4_opacity' => $form_state->getValue('h4_opacity'),
    'h4_font_size' => $form_state->getValue('h4_font_size'),
    'h4_font_size_unit' => $form_state->getValue('h4_font_size_unit'),
    'h4_font_size_min' => $form_state->getValue('h4_font_size_min'),
    'h4_line_height' => $form_state->getValue('h4_line_height'),
    'h4_font_weight' => $form_state->getValue('h4_font_weight'),
    'h4_font_style' => $form_state->getValue('h4_font_style'),
    'h4_margin_top' => $form_state->getValue('h4_margin_top'),
    'h4_margin_bottom' => $form_state->getValue('h4_margin_bottom'),
    'h4_margin_unit' => $form_state->getValue('h4_margin_unit'),

    'h5_font_family' => $form_state->getValue('h5_font_family'),
    'h5_color' => $form_state->getValue('h5_color'),
    'h5_opacity' => $form_state->getValue('h5_opacity'),
    'h5_font_size' => $form_state->getValue('h5_font_size'),
    'h5_font_size_unit' => $form_state->getValue('h5_font_size_unit'),
    'h5_font_size_min' => $form_state->getValue('h5_font_size_min'),
    'h5_line_height' => $form_state->getValue('h5_line_height'),
    'h5_font_weight' => $form_state->getValue('h5_font_weight'),
    'h5_font_style' => $form_state->getValue('h5_font_style'),
    'h5_margin_top' => $form_state->getValue('h5_margin_top'),
    'h5_margin_bottom' => $form_state->getValue('h5_margin_bottom'),
    'h5_margin_unit' => $form_state->getValue('h5_margin_unit'),

    'h6_font_family' => $form_state->getValue('h6_font_family'),
    'h6_color' => $form_state->getValue('h6_color'),
    'h6_opacity' => $form_state->getValue('h6_opacity'),
    'h6_font_size' => $form_state->getValue('h6_font_size'),
    'h6_font_size_unit' => $form_state->getValue('h6_font_size_unit'),
    'h6_font_size_min' => $form_state->getValue('h6_font_size_min'),
    'h6_line_height' => $form_state->getValue('h6_line_height'),
    'h6_font_weight' => $form_state->getValue('h6_font_weight'),
    'h6_font_style' => $form_state->getValue('h6_font_style'),
    'h6_margin_top' => $form_state->getValue('h6_margin_top'),
    'h6_margin_bottom' => $form_state->getValue('h6_margin_bottom'),
    'h6_margin_unit' => $form_state->getValue('h6_margin_unit'),

    'standard_font_family' => $form_state->getValue('standard_font_family'),
    'standard_color' => $form_state->getValue('standard_color'),
    'standard_opacity' => $form_state->getValue('standard_opacity'),
    'standard_font_size' => $form_state->getValue('standard_font_size'),
    'standard_font_size_unit' => $form_state->getValue('standard_font_size_unit'),
    'standard_font_size_min' => $form_state->getValue('standard_font_size_min'),
    'standard_line_height' => $form_state->getValue('standard_line_height'),
    'standard_font_weight' => $form_state->getValue('standard_font_weight'),
    'standard_font_style' => $form_state->getValue('standard_font_style'),
    'standard_margin_top' => $form_state->getValue('standard_margin_top'),
    'standard_margin_bottom' => $form_state->getValue('standard_margin_bottom'),
    'standard_margin_unit' => $form_state->getValue('standard_margin_unit'),

    'small_font_family' => $form_state->getValue('small_font_family'),
    'small_color' => $form_state->getValue('small_color'),
    'small_opacity' => $form_state->getValue('small_opacity'),
    'small_font_size' => $form_state->getValue('small_font_size'),
    'small_font_size_unit' => $form_state->getValue('small_font_size_unit'),
    'small_font_size_min' => $form_state->getValue('small_font_size_min'),
    'small_line_height' => $form_state->getValue('small_line_height'),
    'small_font_weight' => $form_state->getValue('small_font_weight'),
    'small_font_style' => $form_state->getValue('small_font_style'),
    'small_margin_top' => $form_state->getValue('small_margin_top'),
    'small_margin_bottom' => $form_state->getValue('small_margin_bottom'),
    'small_margin_unit' => $form_state->getValue('small_margin_unit'),

    'lead_font_family' => $form_state->getValue('lead_font_family'),
    'lead_color' => $form_state->getValue('lead_color'),
    'lead_opacity' => $form_state->getValue('lead_opacity'),
    'lead_font_size' => $form_state->getValue('lead_font_size'),
    'lead_font_size_unit' => $form_state->getValue('lead_font_size_unit'),
    'lead_font_size_min' => $form_state->getValue('lead_font_size_min'),
    'lead_line_height' => $form_state->getValue('lead_line_height'),
    'lead_font_weight' => $form_state->getValue('lead_font_weight'),
    'lead_font_style' => $form_state->getValue('lead_font_style'),
    'lead_margin_top' => $form_state->getValue('lead_margin_top'),
    'lead_margin_bottom' => $form_state->getValue('lead_margin_bottom'),
    'lead_margin_unit' => $form_state->getValue('lead_margin_unit'),

    'deco_1_font_family' => $form_state->getValue('deco_1_font_family'),
    'deco_1_color' => $form_state->getValue('deco_1_color'),
    'deco_1_opacity' => $form_state->getValue('deco_1_opacity'),
    'deco_1_font_size' => $form_state->getValue('deco_1_font_size'),
    'deco_1_font_size_unit' => $form_state->getValue('deco_1_font_size_unit'),
    'deco_1_font_size_min' => $form_state->getValue('deco_1_font_size_min'),
    'deco_1_line_height' => $form_state->getValue('deco_1_line_height'),
    'deco_1_font_weight' => $form_state->getValue('deco_1_font_weight'),
    'deco_1_font_style' => $form_state->getValue('deco_1_font_style'),
    'deco_1_margin_top' => $form_state->getValue('deco_1_margin_top'),
    'deco_1_margin_bottom' => $form_state->getValue('deco_1_margin_bottom'),
    'deco_1_margin_unit' => $form_state->getValue('deco_1_margin_unit'),

    'deco_2_font_family' => $form_state->getValue('deco_2_font_family'),
    'deco_2_color' => $form_state->getValue('deco_2_color'),
    'deco_2_opacity' => $form_state->getValue('deco_2_opacity'),
    'deco_2_font_size' => $form_state->getValue('deco_2_font_size'),
    'deco_2_font_size_unit' => $form_state->getValue('deco_2_font_size_unit'),
    'deco_2_font_size_min' => $form_state->getValue('deco_2_font_size_min'),
    'deco_2_line_height' => $form_state->getValue('deco_2_line_height'),
    'deco_2_font_weight' => $form_state->getValue('deco_2_font_weight'),
    'deco_2_font_style' => $form_state->getValue('deco_2_font_style'),
    'deco_2_margin_top' => $form_state->getValue('deco_2_margin_top'),
    'deco_2_margin_bottom' => $form_state->getValue('deco_2_margin_bottom'),
    'deco_2_margin_unit' => $form_state->getValue('deco_2_margin_unit'),

    'deco_3_font_family' => $form_state->getValue('deco_3_font_family'),
    'deco_3_color' => $form_state->getValue('deco_3_color'),
    'deco_3_opacity' => $form_state->getValue('deco_3_opacity'),
    'deco_3_font_size' => $form_state->getValue('deco_3_font_size'),
    'deco_3_font_size_unit' => $form_state->getValue('deco_3_font_size_unit'),
    'deco_3_font_size_min' => $form_state->getValue('deco_3_font_size_min'),
    'deco_3_line_height' => $form_state->getValue('deco_3_line_height'),
    'deco_3_font_weight' => $form_state->getValue('deco_3_font_weight'),
    'deco_3_font_style' => $form_state->getValue('deco_3_font_style'),
    'deco_3_margin_top' => $form_state->getValue('deco_3_margin_top'),
    'deco_3_margin_bottom' => $form_state->getValue('deco_3_margin_bottom'),
    'deco_3_margin_unit' => $form_state->getValue('deco_3_margin_unit'),


    'link_color' => $form_state->getValue('link_color'),
    'link_opacity' => $form_state->getValue('link_opacity'),
    'link_text_decoration' => $form_state->getValue('link_text_decoration'),
    'link_color_hover' => $form_state->getValue('link_color_hover'),
    'link_opacity_hover' => $form_state->getValue('link_opacity_hover'),
    'link_text_decoration_hover' => $form_state->getValue('link_text_decoration_hover'),


    'button_font_family' => $form_state->getValue('button_font_family'),
    'button_font_weight' => $form_state->getValue('button_font_weight'),
    'button_font_style' => $form_state->getValue('button_font_style'),
    'button_font_size' => $form_state->getValue('button_font_size'),
    'button_font_size_unit' => $form_state->getValue('button_font_size_unit'),
    'button_margin_top' => $form_state->getValue('button_margin_top'),
    'button_margin_right' => $form_state->getValue('button_margin_right'),
    'button_margin_bottom' => $form_state->getValue('button_margin_bottom'),
    'button_margin_left' => $form_state->getValue('button_margin_left'),
    'button_margin_unit' => $form_state->getValue('button_margin_unit'),
    'button_padding_top' => $form_state->getValue('button_padding_top'),
    'button_padding_right' => $form_state->getValue('button_padding_right'),
    'button_padding_bottom' => $form_state->getValue('button_padding_bottom'),
    'button_padding_left' => $form_state->getValue('button_padding_left'),
    'button_padding_unit' => $form_state->getValue('button_padding_unit'),
    'button_border_width_top' => $form_state->getValue('button_border_width_top'),
    'button_border_width_right' => $form_state->getValue('button_border_width_right'),
    'button_border_width_bottom' => $form_state->getValue('button_border_width_bottom'),
    'button_border_width_left' => $form_state->getValue('button_border_width_left'),
    'button_border_width_unit' => $form_state->getValue('button_border_width_unit'),
    'button_border_radius' => $form_state->getValue('button_border_radius'),
    'button_border_radius_unit' => $form_state->getValue('button_border_radius_unit'),

    'button_font_color_standard' => $form_state->getValue('button_font_color_standard'),
    'button_font_opacity_standard' => $form_state->getValue('button_font_opacity_standard'),
    'button_background_color_standard' => $form_state->getValue('button_background_color_standard'),
    'button_background_opacity_standard' => $form_state->getValue('button_background_opacity_standard'),
    'button_border_color_standard' => $form_state->getValue('button_border_color_standard'),
    'button_border_opacity_standard' => $form_state->getValue('button_border_opacity_standard'),
    'button_font_color_hover' => $form_state->getValue('button_font_color_hover'),
    'button_font_opacity_hover' => $form_state->getValue('button_font_opacity_hover'),
    'button_background_color_hover' => $form_state->getValue('button_background_color_hover'),
    'button_background_opacity_hover' => $form_state->getValue('button_background_opacity_hover'),
    'button_border_color_hover' => $form_state->getValue('button_border_color_hover'),
    'button_border_opacity_hover' => $form_state->getValue('button_border_opacity_hover'),
    'button_font_color_active' => $form_state->getValue('button_font_color_active'),
    'button_font_opacity_active' => $form_state->getValue('button_font_opacity_active'),
    'button_background_color_active' => $form_state->getValue('button_background_color_active'),
    'button_background_opacity_active' => $form_state->getValue('button_background_opacity_active'),
    'button_border_color_active' => $form_state->getValue('button_border_color_active'),
    'button_border_opacity_active' => $form_state->getValue('button_border_opacity_active'),
    'button_font_color_inverted' => $form_state->getValue('button_font_color_inverted'),
    'button_font_opacity_inverted' => $form_state->getValue('button_font_opacity_inverted'),
    'button_background_color_inverted' => $form_state->getValue('button_background_color_inverted'),
    'button_background_opacity_inverted' => $form_state->getValue('button_background_opacity_inverted'),
    'button_border_color_inverted' => $form_state->getValue('button_border_color_inverted'),
    'button_border_opacity_standard' => $form_state->getValue('button_border_opacity_standard'),
    'button_font_color_inverted_hover' => $form_state->getValue('button_font_color_inverted_hover'),
    'button_font_opacity_inverted_hover' => $form_state->getValue('button_font_opacity_inverted_hover'),
    'button_background_color_inverted_hover' => $form_state->getValue('button_background_color_inverted_hover'),
    'button_background_opacity_inverted_hover' => $form_state->getValue('button_background_opacity_inverted_hover'),
    'button_border_color_inverted_hover' => $form_state->getValue('button_border_color_inverted_hover'),
    'button_border_opacity_inverted_hover' => $form_state->getValue('button_border_opacity_inverted_hover'),
    'button_font_color_inverted_active' => $form_state->getValue('button_font_color_inverted_active'),
    'button_font_opacity_inverted_active' => $form_state->getValue('button_font_opacity_inverted_active'),
    'button_background_color_inverted_active' => $form_state->getValue('button_background_color_inverted_active'),
    'button_background_opacity_inverted_active' => $form_state->getValue('button_background_opacity_inverted_active'),
    'button_border_color_inverted_active' => $form_state->getValue('button_border_color_inverted_active'),
    'button_border_opacity_inverted_active' => $form_state->getValue('button_border_opacity_inverted_active'),



    'button_alternate_font_size' => $form_state->getValue('button_alternate_font_size'),
    'button_alternate_font_size_unit' => $form_state->getValue('button_alternate_font_size_unit'),
    'button_alternate_font_weight' => $form_state->getValue('button_alternate_font_weight'),
    'button_alternate_font_style' => $form_state->getValue('button_alternate_font_style'),
    'button_alternate_font_family' => $form_state->getValue('button_alternate_font_family'),
    'button_alternate_margin_top' => $form_state->getValue('button_alternate_margin_top'),
    'button_alternate_margin_unit' => $form_state->getValue('button_alternate_margin_unit'),
    'button_alternate_margin_right' => $form_state->getValue('button_alternate_margin_right'),
    'button_alternate_margin_bottom' => $form_state->getValue('button_alternate_margin_bottom'),
    'button_alternate_margin_left' => $form_state->getValue('button_alternate_margin_left'),
    'button_alternate_padding_top' => $form_state->getValue('button_alternate_padding_top'),
    'button_alternate_padding_unit' => $form_state->getValue('button_alternate_padding_unit'),
    'button_alternate_padding_right' => $form_state->getValue('button_alternate_padding_right'),
    'button_alternate_padding_bottom' => $form_state->getValue('button_alternate_padding_bottom'),
    'button_alternate_padding_left' => $form_state->getValue('button_alternate_padding_left'),
    'button_alternate_border_width_top' => $form_state->getValue('button_alternate_border_width_top'),
    'button_alternate_border_width_right' => $form_state->getValue('button_alternate_border_width_right'),
    'button_alternate_border_width_bottom' => $form_state->getValue('button_alternate_border_width_bottom'),
    'button_alternate_border_width_left' => $form_state->getValue('button_alternate_border_width_left'),
    'button_alternate_border_width_unit' => $form_state->getValue('button_alternate_border_width_unit'),
    'button_alternate_border_radius' => $form_state->getValue('button_alternate_border_radius'),
    'button_alternate_border_radius_unit' => $form_state->getValue('button_alternate_border_radius_unit'),
    'button_alternate_font_color_standard' => $form_state->getValue('button_alternate_font_color_standard'),
    'button_alternate_font_opacity_standard' => $form_state->getValue('button_alternate_font_opacity_standard'),
    'button_alternate_background_color_standard' => $form_state->getValue('button_alternate_background_color_standard'),
    'button_alternate_background_opacity_standard' => $form_state->getValue('button_alternate_background_opacity_standard'),
    'button_alternate_border_color_standard' => $form_state->getValue('button_alternate_border_color_standard'),
    'button_alternate_border_opacity_standard' => $form_state->getValue('button_alternate_border_opacity_standard'),
    'button_alternate_font_color_hover' => $form_state->getValue('button_alternate_font_color_hover'),
    'button_alternate_font_opacity_hover' => $form_state->getValue('button_alternate_font_opacity_hover'),
    'button_alternate_background_color_hover' => $form_state->getValue('button_alternate_background_color_hover'),
    'button_alternate_background_opacity_hover' => $form_state->getValue('button_alternate_background_opacity_hover'),
    'button_alternate_border_color_hover' => $form_state->getValue('button_alternate_border_color_hover'),
    'button_alternate_border_opacity_hover' => $form_state->getValue('button_alternate_border_opacity_hover'),
    'button_alternate_font_color_active' => $form_state->getValue('button_alternate_font_color_active'),
    'button_alternate_font_opacity_active' => $form_state->getValue('button_alternate_font_opacity_active'),
    'button_alternate_background_color_active' => $form_state->getValue('button_alternate_background_color_active'),
    'button_alternate_background_opacity_active' => $form_state->getValue('button_alternate_background_opacity_active'),
    'button_alternate_border_color_active' => $form_state->getValue('button_alternate_border_color_active'),
    'button_alternate_border_opacity_active' => $form_state->getValue('button_alternate_border_opacity_active'),
    'button_alternate_font_color_inverted' => $form_state->getValue('button_alternate_font_color_inverted'),
    'button_alternate_font_opacity_inverted' => $form_state->getValue('button_alternate_font_opacity_inverted'),
    'button_alternate_background_color_inverted' => $form_state->getValue('button_alternate_background_color_inverted'),
    'button_alternate_background_opacity_inverted' => $form_state->getValue('button_alternate_background_opacity_inverted'),
    'button_alternate_border_color_inverted' => $form_state->getValue('button_alternate_border_color_inverted'),
    'button_alternate_border_opacity_standard' => $form_state->getValue('button_alternate_border_opacity_standard'),
    'button_alternate_font_color_inverted_hover' => $form_state->getValue('button_alternate_font_color_inverted_hover'),
    'button_alternate_font_opacity_inverted_hover' => $form_state->getValue('button_alternate_font_opacity_inverted_hover'),
    'button_alternate_background_color_inverted_hover' => $form_state->getValue('button_alternate_background_color_inverted_hover'),
    'button_alternate_background_opacity_inverted_hover' => $form_state->getValue('button_alternate_background_opacity_inverted_hover'),
    'button_alternate_border_color_inverted_hover' => $form_state->getValue('button_alternate_border_color_inverted_hover'),
    'button_alternate_border_opacity_inverted_hover' => $form_state->getValue('button_alternate_border_opacity_inverted_hover'),
    'button_alternate_font_color_inverted_active' => $form_state->getValue('button_alternate_font_color_inverted_active'),
    'button_alternate_font_opacity_inverted_active' => $form_state->getValue('button_alternate_font_opacity_inverted_active'),
    'button_alternate_background_color_inverted_active' => $form_state->getValue('button_alternate_background_color_inverted_active'),
    'button_alternate_background_opacity_inverted_active' => $form_state->getValue('button_alternate_background_opacity_inverted_active'),
    'button_alternate_border_color_inverted_active' => $form_state->getValue('button_alternate_border_color_inverted_active'),
    'button_alternate_border_opacity_inverted_active' => $form_state->getValue('button_alternate_border_opacity_inverted_active'),







    'border_width' => $form_state->getValue('border_width'),
    'border_width_unit' => $form_state->getValue('border_width_unit'),
    'border_style' => $form_state->getValue('border_style'),
    'border_color' => $form_state->getValue('border_color'),
    'border_opacity' => $form_state->getValue('border_opacity'),
    'radius' => $form_state->getValue('radius'),
    'radius_unit' => $form_state->getValue('radius_unit'),

    'margin_top' => $form_state->getValue('margin_top'),
    'margin_right' => $form_state->getValue('margin_right'),
    'margin_bottom' => $form_state->getValue('margin_bottom'),
    'margin_left' => $form_state->getValue('margin_left'),
    'margin_unit' => $form_state->getValue('margin_unit'),

    'padding_top' => $form_state->getValue('padding_top'),
    'padding_right' => $form_state->getValue('padding_right'),
    'padding_bottom' => $form_state->getValue('padding_bottom'),
    'padding_left' => $form_state->getValue('padding_left'),
    'padding_unit' => $form_state->getValue('padding_unit'),


    'slider_arrow_size' => $form_state->getValue('slider_arrow_size'),
    'slider_arrow_size_unit' => $form_state->getValue('slider_arrow_size_unit'),
    'slider_arrow_color' => $form_state->getValue('slider_arrow_color'),
    'slider_arrow_opacity' => $form_state->getValue('slider_arrow_opacity'),
    'slider_arrow_backgroundcolor' => $form_state->getValue('slider_arrow_backgroundcolor'),
    'slider_arrow_background_opacity' => $form_state->getValue('slider_arrow_background_opacity'),

    'slider_dot_size' => $form_state->getValue('slider_dot_size'),
    'slider_dot_size_unit' => $form_state->getValue('slider_dot_size_unit'),
    'slider_dot_color' => $form_state->getValue('slider_dot_color'),
    'slider_dot_opacity' => $form_state->getValue('slider_dot_opacity'),
    'slider_dot_color_active' => $form_state->getValue('slider_dot_color_active'),
    'slider_dot_opacity_active' => $form_state->getValue('slider_dot_opacity_active'),

    'quote_highlight_color' => $form_state->getValue('quote_highlight_color'),
    'quote_highlight_opacity' => $form_state->getValue('quote_highlight_opacity'),

    'social_icon_color' => $form_state->getValue('social_icon_color'),
    'social_icon_opacity' => $form_state->getValue('social_icon_opacity'),

    'tab_color' => $form_state->getValue('tab_color'),
    'tab_opacity' => $form_state->getValue('tab_opacity'),
    'tab_color_active' => $form_state->getValue('tab_color_active'),
    'tab_opacity_active' => $form_state->getValue('tab_opacity_active'),
    'tab_font_color' => $form_state->getValue('tab_font_color'),
    'tab_font_opacity' => $form_state->getValue('tab_font_opacity'),
    'tab_font_color_active' => $form_state->getValue('tab_font_color_active'),
    'tab_font_opacity_active' => $form_state->getValue('tab_font_opacity_active'),



    'toggler_color' => $form_state->getValue('toggler_color'),
    'toggler_opacity' => $form_state->getValue('toggler_opacity'),
    'toggler_color_hover' => $form_state->getValue('toggler_color_hover'),
    'toggler_opacity_hover' => $form_state->getValue('toggler_opacity_hover'),
    'toggler_color_active' => $form_state->getValue('toggler_color_active'),
    'toggler_opacity_active' => $form_state->getValue('toggler_opacity_active'),



    'anchornavigation_font_family' => $form_state->getValue('anchornavigation_font_family'),
    'anchornavigation_font_weight' => $form_state->getValue('anchornavigation_font_weight'),
    'anchornavigation_font_style' => $form_state->getValue('anchornavigation_font_style'),
    'anchornavigation_line_height' => $form_state->getValue('anchornavigation_line_height'),
    'anchornavigation_font_size' => $form_state->getValue('anchornavigation_font_size'),
    'anchornavigation_font_size_unit' => $form_state->getValue('anchornavigation_font_size_unit'),
    'anchornavigation_margin_top' => $form_state->getValue('anchornavigation_margin_top'),
    'anchornavigation_margin_right' => $form_state->getValue('anchornavigation_margin_right'),
    'anchornavigation_margin_bottom' => $form_state->getValue('anchornavigation_margin_bottom'),
    'anchornavigation_margin_left' => $form_state->getValue('anchornavigation_margin_left'),
    'anchornavigation_margin_unit' => $form_state->getValue('anchornavigation_margin_unit'),
    'anchornavigation_padding_top' => $form_state->getValue('anchornavigation_padding_top'),
    'anchornavigation_padding_right' => $form_state->getValue('anchornavigation_padding_right'),
    'anchornavigation_padding_bottom' => $form_state->getValue('anchornavigation_padding_bottom'),
    'anchornavigation_padding_left' => $form_state->getValue('anchornavigation_padding_left'),
    'anchornavigation_padding_unit' => $form_state->getValue('anchornavigation_padding_unit'),
    'anchornavigation_font_color_standard' => $form_state->getValue('anchornavigation_font_color_standard'),
    'anchornavigation_font_opacity_standard' => $form_state->getValue('anchornavigation_font_opacity_standard'),
    'anchornavigation_background_color_standard' => $form_state->getValue('anchornavigation_background_color_standard'),
    'anchornavigation_background_opacity_standard' => $form_state->getValue('anchornavigation_background_opacity_standard'),
    'anchornavigation_border_color_standard' => $form_state->getValue('anchornavigation_border_color_standard'),
    'anchornavigation_border_opacity_standard' => $form_state->getValue('anchornavigation_border_opacity_standard'),
    'anchornavigation_font_color_hover' => $form_state->getValue('anchornavigation_font_color_hover'),
    'anchornavigation_font_opacity_hover' => $form_state->getValue('anchornavigation_font_opacity_hover'),
    'anchornavigation_background_color_hover' => $form_state->getValue('anchornavigation_background_color_hover'),
    'anchornavigation_background_opacity_hover' => $form_state->getValue('anchornavigation_background_opacity_hover'),
    'anchornavigation_border_color_hover' => $form_state->getValue('anchornavigation_border_color_hover'),
    'anchornavigation_border_opacity_hover' => $form_state->getValue('anchornavigation_border_opacity_hover'),
    'anchornavigation_font_color_active' => $form_state->getValue('anchornavigation_font_color_active'),
    'anchornavigation_font_opacity_active' => $form_state->getValue('anchornavigation_font_opacity_active'),
    'anchornavigation_background_color_active' => $form_state->getValue('anchornavigation_background_color_active'),
    'anchornavigation_background_opacity_active' => $form_state->getValue('anchornavigation_background_opacity_active'),
    'anchornavigation_border_color_active' => $form_state->getValue('anchornavigation_border_color_active'),
    'anchornavigation_border_opacity_active' => $form_state->getValue('anchornavigation_border_opacity_active'),
    'anchornavigation_wrapper_background_color' => $form_state->getValue('anchornavigation_wrapper_background_color'),
    'anchornavigation_wrapper_background_opacity' => $form_state->getValue('anchornavigation_wrapper_background_opacity'),





  ];


  $filename = __DIR__ . "/resources/sass/_definitions.scss";

  // $service = \Drupal::service('iq_barrio.update_theme');
  // $service->set_pattern_theme($arrKeywords,$filename);

  $service = new \Drupal\iq_barrio\Service\ThemeServices();
  $service->set_pattern_theme($arrKeywords, $filename);

  //Call hook
  \Drupal::moduleHandler()->invokeAll('iq_theme_settings', array($arrKeywords, $service));
}

function iq_barrio_theme_rebuild()
{
//  \Drupal::logger('iq_barrio')->notice('cache rebuild :)');
}


function iq_barrio_ui_patterns_info_alter(array &$definitions) {
  //    print_r( $definitions );
    $definitions['yaml:rowoneone']->setLabel('blablablaba');
  }
